// ══════════════════════════════════════════
// Hub RPG — Importação Magias SRD 3.5
// PT-BR primeiro, EN como referência
// ══════════════════════════════════════════

import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" });
const prisma = new PrismaClient({ adapter });

interface Spell35 {
  index: string;
  name: string;
  namePtBr: string;
  level: number;
  school: string;
  castingTime: string;
  range: string;
  duration: string;
  components: string;
  description: string;
  descriptionPtBr: string;
  classes: string;
}

const SPELLS_35: Spell35[] = [
  // ── Nível 0 (Truques) ──────────────────
  { index: "acid-splash-35", name: "Acid Splash", namePtBr: "Borrifo Ácido", level: 0, school: "Conjuration", castingTime: "1 action", range: "Close (25 ft + 5 ft/2 levels)", duration: "Instantaneous", components: "V, S", description: "You fire a small orb of acid at the target for 1d3 acid damage.", descriptionPtBr: "Dispara um pequeno orbe de ácido causando 1d3 de dano ácido. Ataque de toque à distância.", classes: "Sorcerer, Wizard" },
  { index: "dancing-lights-35", name: "Dancing Lights", namePtBr: "Luzes Dançantes", level: 0, school: "Evocation", castingTime: "1 action", range: "Medium (100 ft + 10 ft/level)", duration: "1 minute", components: "V, S", description: "Creates up to four lights that resemble lanterns or torches.", descriptionPtBr: "Cria até 4 luzes que lembram tochas ou lanternas, que você pode mover.", classes: "Bard, Sorcerer, Wizard" },
  { index: "daze-35", name: "Daze", namePtBr: "Pasmar", level: 0, school: "Enchantment", castingTime: "1 action", range: "Close", duration: "1 round", components: "V, S, M", description: "A humanoid creature of 4 HD or less loses its next action.", descriptionPtBr: "Humanoide com 4 DV ou menos perde sua próxima ação. Vontade nega.", classes: "Bard, Sorcerer, Wizard" },
  { index: "detect-magic-35", name: "Detect Magic", namePtBr: "Detectar Magia", level: 0, school: "Divination", castingTime: "1 action", range: "60 ft", duration: "Concentration, up to 1 min/level", components: "V, S", description: "You detect magical auras. Can identify school of magic.", descriptionPtBr: "Detecta auras mágicas em cone de 18m. Pode identificar a escola de magia.", classes: "Bard, Cleric, Druid, Sorcerer, Wizard" },
  { index: "detect-poison-35", name: "Detect Poison", namePtBr: "Detectar Veneno", level: 0, school: "Divination", castingTime: "1 action", range: "Close", duration: "Instantaneous", components: "V, S", description: "You determine whether a creature, object, or area has been poisoned.", descriptionPtBr: "Determina se uma criatura, objeto ou área foi envenenada.", classes: "Cleric, Druid, Paladin, Ranger, Sorcerer, Wizard" },
  { index: "disrupt-undead-35", name: "Disrupt Undead", namePtBr: "Perturbar Morto-Vivo", level: 0, school: "Necromancy", castingTime: "1 action", range: "Close", duration: "Instantaneous", components: "V, S", description: "You direct a ray of positive energy. Deals 1d6 damage to undead.", descriptionPtBr: "Raio de energia positiva que causa 1d6 de dano a mortos-vivos.", classes: "Sorcerer, Wizard" },
  { index: "flare-35", name: "Flare", namePtBr: "Clarão", level: 0, school: "Evocation", castingTime: "1 action", range: "Close", duration: "Instantaneous", components: "V", description: "A burst of light dazzles one creature (-1 on attack rolls).", descriptionPtBr: "Clarão de luz que ofusca uma criatura (-1 nas jogadas de ataque). Fortitude nega.", classes: "Bard, Druid, Sorcerer, Wizard" },
  { index: "ghost-sound-35", name: "Ghost Sound", namePtBr: "Som Fantasma", level: 0, school: "Illusion", castingTime: "1 action", range: "Close", duration: "1 round/level", components: "V, S, M", description: "Creates a volume of sound that can rise from a whisper to a roar.", descriptionPtBr: "Cria sons ilusórios. Volume máximo de quatro humanos por nível de conjurador.", classes: "Bard, Sorcerer, Wizard" },
  { index: "guidance-35", name: "Guidance", namePtBr: "Orientação", level: 0, school: "Divination", castingTime: "1 action", range: "Touch", duration: "1 minute", components: "V, S", description: "The subject gets a +1 competence bonus on a single attack roll, saving throw, or skill check.", descriptionPtBr: "+1 bônus de competência em uma jogada de ataque, salvaguarda ou perícia.", classes: "Cleric, Druid" },
  { index: "light-35", name: "Light", namePtBr: "Luz", level: 0, school: "Evocation", castingTime: "1 action", range: "Touch", duration: "10 min/level", components: "V, M", description: "Object touched sheds light as a torch.", descriptionPtBr: "Objeto tocado brilha como uma tocha (raio de 6m).", classes: "Bard, Cleric, Druid, Sorcerer, Wizard" },
  { index: "mage-hand-35", name: "Mage Hand", namePtBr: "Mão Arcana", level: 0, school: "Transmutation", castingTime: "1 action", range: "Close", duration: "Concentration", components: "V, S", description: "You point at an object and can lift it and move it at will (up to 5 pounds).", descriptionPtBr: "Move telecineticamente um objeto de até 2,5 kg à distância.", classes: "Bard, Sorcerer, Wizard" },
  { index: "mending-35", name: "Mending", namePtBr: "Consertar", level: 0, school: "Transmutation", castingTime: "1 action", range: "10 ft", duration: "Instantaneous", components: "V, S", description: "Repairs small breaks or tears in objects.", descriptionPtBr: "Repara pequenas quebras ou rasgos em objetos (até 0,5 kg).", classes: "Bard, Cleric, Druid, Sorcerer, Wizard" },
  { index: "message-35", name: "Message", namePtBr: "Mensagem", level: 0, school: "Transmutation", castingTime: "1 action", range: "Medium", duration: "10 min/level", components: "V, S, F", description: "You can whisper messages and receive whispered replies.", descriptionPtBr: "Sussurrar mensagens e receber respostas sussurradas à distância.", classes: "Bard, Sorcerer, Wizard" },
  { index: "prestidigitation-35", name: "Prestidigitation", namePtBr: "Prestidigitação", level: 0, school: "Universal", castingTime: "1 action", range: "10 ft", duration: "1 hour", components: "V, S", description: "Performs minor tricks like creating small sensory effects.", descriptionPtBr: "Truques menores: limpar, sujar, aquecer, resfriar, colorir, criar bugigangas.", classes: "Bard, Sorcerer, Wizard" },
  { index: "ray-of-frost-35", name: "Ray of Frost", namePtBr: "Raio de Gelo", level: 0, school: "Evocation", castingTime: "1 action", range: "Close", duration: "Instantaneous", components: "V, S", description: "A ray of freezing air and ice deals 1d3 cold damage.", descriptionPtBr: "Raio de ar congelante causa 1d3 de dano de frio. Ataque de toque à distância.", classes: "Sorcerer, Wizard" },
  { index: "read-magic-35", name: "Read Magic", namePtBr: "Ler Magias", level: 0, school: "Divination", castingTime: "1 action", range: "Personal", duration: "10 min/level", components: "V, S, F", description: "You can decipher magical inscriptions that would otherwise be unintelligible.", descriptionPtBr: "Decifrar inscrições mágicas, pergaminhos e grimórios.", classes: "Bard, Cleric, Druid, Paladin, Ranger, Sorcerer, Wizard" },
  { index: "resistance-35", name: "Resistance", namePtBr: "Resistência", level: 0, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "1 minute", components: "V, S, M", description: "The subject gains a +1 resistance bonus on saving throws.", descriptionPtBr: "+1 bônus de resistência em testes de salvaguarda.", classes: "Bard, Cleric, Druid, Paladin, Sorcerer, Wizard" },
  { index: "virtue-35", name: "Virtue", namePtBr: "Virtude", level: 0, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 minute", components: "V, S, DF", description: "The subject gains 1 temporary hit point.", descriptionPtBr: "Alvo ganha 1 ponto de vida temporário.", classes: "Cleric, Paladin" },

  // ── Nível 1 ────────────────────────────
  { index: "alarm-35", name: "Alarm", namePtBr: "Alarme", level: 1, school: "Abjuration", castingTime: "1 action", range: "Close", duration: "2 hours/level", components: "V, S, F/DF", description: "Alarm warns you of intruders. Mental or audible alarm.", descriptionPtBr: "Alarme mental ou audível que avisa sobre intrusos em área de 6m.", classes: "Bard, Ranger, Sorcerer, Wizard" },
  { index: "bless-35", name: "Bless", namePtBr: "Abençoar", level: 1, school: "Enchantment", castingTime: "1 action", range: "50 ft", duration: "1 min/level", components: "V, S, DF", description: "Allies gain +1 morale bonus on attack rolls and saves vs. fear.", descriptionPtBr: "Aliados ganham +1 bônus moral no ataque e salvaguardas contra medo.", classes: "Cleric, Paladin" },
  { index: "burning-hands-35", name: "Burning Hands", namePtBr: "Mãos Flamejantes", level: 1, school: "Evocation", castingTime: "1 action", range: "15 ft cone", duration: "Instantaneous", components: "V, S", description: "A cone of searing flame shoots from your fingertips. 1d4/level fire damage (max 5d4).", descriptionPtBr: "Cone de chamas dos dedos. 1d4/nível de dano de fogo (máx 5d4). Reflexos metade.", classes: "Sorcerer, Wizard" },
  { index: "charm-person-35", name: "Charm Person", namePtBr: "Enfeitiçar Pessoa", level: 1, school: "Enchantment", castingTime: "1 action", range: "Close", duration: "1 hour/level", components: "V, S", description: "Makes one humanoid your friend. Will save negates.", descriptionPtBr: "Um humanoide o trata como grande amigo. Vontade nega. +5 se em combate.", classes: "Bard, Sorcerer, Wizard" },
  { index: "color-spray-35", name: "Color Spray", namePtBr: "Borrifo de Cores", level: 1, school: "Illusion", castingTime: "1 action", range: "15 ft cone", duration: "See text", components: "V, S, M", description: "A vivid cone of clashing colors causes creatures to become stunned, blinded, and/or unconscious.", descriptionPtBr: "Cone de cores vibrantes. Criaturas ficam atordoadas, cegas ou inconscientes conforme DV.", classes: "Sorcerer, Wizard" },
  { index: "cure-light-wounds-35", name: "Cure Light Wounds", namePtBr: "Curar Ferimentos Leves", level: 1, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", components: "V, S", description: "Cures 1d8 damage +1/level (max +5).", descriptionPtBr: "Cura 1d8 +1/nível (máx +5) de dano. Causa dano a mortos-vivos.", classes: "Bard, Cleric, Druid, Paladin, Ranger" },
  { index: "detect-evil-35", name: "Detect Evil", namePtBr: "Detectar o Mal", level: 1, school: "Divination", castingTime: "1 action", range: "60 ft cone", duration: "Concentration, up to 10 min/level", components: "V, S, DF", description: "You can sense the presence of evil.", descriptionPtBr: "Detecta a presença e intensidade do mal em cone de 18m.", classes: "Cleric" },
  { index: "divine-favor-35", name: "Divine Favor", namePtBr: "Favor Divino", level: 1, school: "Evocation", castingTime: "1 action", range: "Personal", duration: "1 minute", components: "V, S, DF", description: "You gain +1 luck bonus per 3 caster levels (max +3) on attack and damage.", descriptionPtBr: "+1/3 níveis (máx +3) bônus de sorte no ataque e dano.", classes: "Cleric, Paladin" },
  { index: "enlarge-person-35", name: "Enlarge Person", namePtBr: "Aumentar Pessoa", level: 1, school: "Transmutation", castingTime: "1 round", range: "Close", duration: "1 min/level", components: "V, S, M", description: "Humanoid creature doubles in height, weight x8. +2 Str, -2 Dex, -1 AC/attack.", descriptionPtBr: "Humanoide dobra de tamanho. +2 FOR, -2 DES, -1 CA/ataque. Tamanho Grande.", classes: "Sorcerer, Wizard" },
  { index: "entangle-35", name: "Entangle", namePtBr: "Enredar", level: 1, school: "Transmutation", castingTime: "1 action", range: "Long (400 ft + 40 ft/level)", duration: "1 min/level", components: "V, S, DF", description: "Grasses, weeds, and other plants wrap around foes.", descriptionPtBr: "Plantas se enroscam nos inimigos. Área de 12m. Reflexos para não ficar preso.", classes: "Druid, Ranger" },
  { index: "expeditious-retreat-35", name: "Expeditious Retreat", namePtBr: "Recuo Expedito", level: 1, school: "Transmutation", castingTime: "1 action", range: "Personal", duration: "1 min/level", components: "V, S", description: "Your base land speed increases by 30 feet.", descriptionPtBr: "Deslocamento terrestre +9m.", classes: "Bard, Sorcerer, Wizard" },
  { index: "grease-35", name: "Grease", namePtBr: "Graxa", level: 1, school: "Conjuration", castingTime: "1 action", range: "Close", duration: "1 round/level", components: "V, S, M", description: "Covers a surface or object with grease making it slippery.", descriptionPtBr: "Cobre superfície com graxa escorregadia. Área 3m ou 1 objeto. Reflexos ou cai.", classes: "Bard, Sorcerer, Wizard" },
  { index: "identify-35", name: "Identify", namePtBr: "Identificar", level: 1, school: "Divination", castingTime: "1 hour", range: "Touch", duration: "Instantaneous", components: "V, S, M (100 gp pearl)", description: "Determines the properties of a magic item.", descriptionPtBr: "Identifica propriedades de um item mágico. Componente: pérola de 100 po.", classes: "Bard, Sorcerer, Wizard" },
  { index: "mage-armor-35", name: "Mage Armor", namePtBr: "Armadura Arcana", level: 1, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "1 hour/level", components: "V, S, F", description: "An invisible field of force surrounds the subject, granting +4 armor bonus to AC.", descriptionPtBr: "Campo de força invisível concede +4 bônus de armadura na CA.", classes: "Sorcerer, Wizard" },
  { index: "magic-missile-35", name: "Magic Missile", namePtBr: "Mísseis Mágicos", level: 1, school: "Evocation", castingTime: "1 action", range: "Medium", duration: "Instantaneous", components: "V, S", description: "A missile of magical energy darts forth dealing 1d4+1 damage. One missile per two caster levels (max 5).", descriptionPtBr: "Mísseis de energia. 1d4+1 cada. 1 míssil a cada 2 níveis (máx 5). Acerta automaticamente.", classes: "Sorcerer, Wizard" },
  { index: "magic-weapon-35", name: "Magic Weapon", namePtBr: "Arma Mágica", level: 1, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, DF", description: "Weapon gains +1 enhancement bonus.", descriptionPtBr: "Arma ganha +1 bônus de aprimoramento no ataque e dano.", classes: "Cleric, Paladin, Sorcerer, Wizard" },
  { index: "protection-from-evil-35", name: "Protection from Evil", namePtBr: "Proteção contra o Mal", level: 1, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M/DF", description: "+2 deflection AC and +2 resistance on saves against evil creatures.", descriptionPtBr: "+2 deflexão na CA e +2 resistência em salvaguardas contra criaturas malignas.", classes: "Cleric, Paladin, Sorcerer, Wizard" },
  { index: "shield-35", name: "Shield", namePtBr: "Escudo Arcano", level: 1, school: "Abjuration", castingTime: "1 action", range: "Personal", duration: "1 min/level", components: "V, S", description: "Shield creates an invisible shield of force that grants +4 shield bonus to AC.", descriptionPtBr: "Escudo de força invisível. +4 bônus de escudo na CA. Bloqueia Mísseis Mágicos.", classes: "Sorcerer, Wizard" },
  { index: "shield-of-faith-35", name: "Shield of Faith", namePtBr: "Escudo da Fé", level: 1, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M", description: "Grants +2 deflection bonus to AC, +1 per 6 caster levels.", descriptionPtBr: "+2 deflexão na CA (+1 a cada 6 níveis, máx +5).", classes: "Cleric" },
  { index: "sleep-35", name: "Sleep", namePtBr: "Sono", level: 1, school: "Enchantment", castingTime: "1 round", range: "Medium", duration: "1 min/level", components: "V, S, M", description: "Causes 4 HD of creatures to fall into magical slumber.", descriptionPtBr: "4 DV de criaturas adormecem magicamente. Sem salvaguarda. Não afeta mortos-vivos.", classes: "Bard, Sorcerer, Wizard" },
  { index: "true-strike-35", name: "True Strike", namePtBr: "Golpe Certeiro", level: 1, school: "Divination", castingTime: "1 action", range: "Personal", duration: "See text", components: "V, F", description: "You gain +20 on your next attack roll.", descriptionPtBr: "+20 de percepção no próximo ataque. Válido até o fim do próximo turno.", classes: "Sorcerer, Wizard" },

  // ── Nível 2 ────────────────────────────
  { index: "aid-35", name: "Aid", namePtBr: "Auxílio", level: 2, school: "Enchantment", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, DF", description: "+1 morale bonus on attack rolls and saves vs. fear, +1d8 temporary HP.", descriptionPtBr: "+1 moral no ataque/salvaguardas contra medo. +1d8 PV temporários.", classes: "Cleric" },
  { index: "bears-endurance-35", name: "Bear's Endurance", namePtBr: "Resistência do Urso", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, DF", description: "Subject gains +4 enhancement bonus to Constitution.", descriptionPtBr: "+4 bônus de aprimoramento em Constituição.", classes: "Cleric, Druid, Ranger, Sorcerer, Wizard" },
  { index: "bulls-strength-35", name: "Bull's Strength", namePtBr: "Força do Touro", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M/DF", description: "Subject gains +4 enhancement bonus to Strength.", descriptionPtBr: "+4 bônus de aprimoramento em Força.", classes: "Cleric, Druid, Paladin, Sorcerer, Wizard" },
  { index: "cats-grace-35", name: "Cat's Grace", namePtBr: "Graça Felina", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M", description: "Subject gains +4 enhancement bonus to Dexterity.", descriptionPtBr: "+4 bônus de aprimoramento em Destreza.", classes: "Bard, Druid, Ranger, Sorcerer, Wizard" },
  { index: "cure-moderate-wounds-35", name: "Cure Moderate Wounds", namePtBr: "Curar Ferimentos Moderados", level: 2, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", components: "V, S", description: "Cures 2d8 +1/level damage (max +10).", descriptionPtBr: "Cura 2d8 +1/nível (máx +10) de dano.", classes: "Bard, Cleric, Druid, Paladin, Ranger" },
  { index: "darkness-35", name: "Darkness", namePtBr: "Escuridão", level: 2, school: "Evocation", castingTime: "1 action", range: "Touch", duration: "10 min/level", components: "V, M/DF", description: "20-ft radius of supernatural shadow.", descriptionPtBr: "Raio de 6m de escuridão sobrenatural. Neutraliza Luz de nível igual ou inferior.", classes: "Bard, Cleric, Sorcerer, Wizard" },
  { index: "eagles-splendor-35", name: "Eagle's Splendor", namePtBr: "Esplendor da Águia", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M/DF", description: "Subject gains +4 enhancement bonus to Charisma.", descriptionPtBr: "+4 bônus de aprimoramento em Carisma.", classes: "Bard, Cleric, Paladin, Sorcerer, Wizard" },
  { index: "foxs-cunning-35", name: "Fox's Cunning", namePtBr: "Astúcia da Raposa", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M/DF", description: "Subject gains +4 enhancement bonus to Intelligence.", descriptionPtBr: "+4 bônus de aprimoramento em Inteligência.", classes: "Bard, Sorcerer, Wizard" },
  { index: "hold-person-35", name: "Hold Person", namePtBr: "Imobilizar Pessoa", level: 2, school: "Enchantment", castingTime: "1 action", range: "Medium", duration: "1 round/level", components: "V, S, F/DF", description: "Paralyzes one humanoid for 1 round/level. Will negates.", descriptionPtBr: "Paralisa um humanoide. Vontade nega. Nova salvaguarda a cada rodada.", classes: "Bard, Cleric, Sorcerer, Wizard" },
  { index: "invisibility-35", name: "Invisibility", namePtBr: "Invisibilidade", level: 2, school: "Illusion", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M/DF", description: "Subject is invisible until it attacks.", descriptionPtBr: "Alvo fica invisível até atacar ou conjurar magia ofensiva.", classes: "Bard, Sorcerer, Wizard" },
  { index: "mirror-image-35", name: "Mirror Image", namePtBr: "Imagem Espelhada", level: 2, school: "Illusion", castingTime: "1 action", range: "Personal", duration: "1 min/level", components: "V, S", description: "Creates 1d4+1 decoy duplicates of you (max 8).", descriptionPtBr: "Cria 1d4+1 duplicatas ilusórias (máx 8). Ataques devem acertar a duplicata.", classes: "Bard, Sorcerer, Wizard" },
  { index: "owls-wisdom-35", name: "Owl's Wisdom", namePtBr: "Sabedoria da Coruja", level: 2, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, M/DF", description: "Subject gains +4 enhancement bonus to Wisdom.", descriptionPtBr: "+4 bônus de aprimoramento em Sabedoria.", classes: "Cleric, Druid, Paladin, Ranger, Sorcerer, Wizard" },
  { index: "resist-energy-35", name: "Resist Energy", namePtBr: "Resistir a Energia", level: 2, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "10 min/level", components: "V, S, DF", description: "Grants creature 10 resistance against specified energy type.", descriptionPtBr: "Resistência 10 contra um tipo de energia (fogo, frio, ácido, elétrico, sônico).", classes: "Cleric, Druid, Paladin, Ranger, Sorcerer, Wizard" },
  { index: "scorching-ray-35", name: "Scorching Ray", namePtBr: "Raio Ardente", level: 2, school: "Evocation", castingTime: "1 action", range: "Close", duration: "Instantaneous", components: "V, S", description: "Ranged touch attack; 4d6 fire damage per ray. One ray + one per four levels (max 3).", descriptionPtBr: "Ataque de toque à distância. 4d6 fogo por raio. 1 raio +1 a cada 4 níveis (máx 3).", classes: "Sorcerer, Wizard" },
  { index: "silence-35", name: "Silence", namePtBr: "Silêncio", level: 2, school: "Illusion", castingTime: "1 round", range: "Long", duration: "1 min/level", components: "V, S", description: "Negates sound in a 20-ft radius. Prevents verbal spellcasting.", descriptionPtBr: "Anula som em raio de 6m. Impede conjuração com componente verbal.", classes: "Bard, Cleric" },
  { index: "web-35", name: "Web", namePtBr: "Teia", level: 2, school: "Conjuration", castingTime: "1 action", range: "Medium", duration: "10 min/level", components: "V, S, M", description: "Fills a 20-ft area with sticky spiderwebs that entangle creatures.", descriptionPtBr: "Teias pegajosas preenchem área de 6m. Prende criaturas. Reflexos para não ficar preso.", classes: "Sorcerer, Wizard" },

  // ── Nível 3 ────────────────────────────
  { index: "cure-serious-wounds-35", name: "Cure Serious Wounds", namePtBr: "Curar Ferimentos Graves", level: 3, school: "Conjuration", castingTime: "1 action", range: "Touch", duration: "Instantaneous", components: "V, S", description: "Cures 3d8 +1/level damage (max +15).", descriptionPtBr: "Cura 3d8 +1/nível (máx +15) de dano.", classes: "Bard, Cleric, Druid, Paladin, Ranger" },
  { index: "dispel-magic-35", name: "Dispel Magic", namePtBr: "Dissipar Magia", level: 3, school: "Abjuration", castingTime: "1 action", range: "Medium", duration: "Instantaneous", components: "V, S", description: "Cancels magical spells and effects. Caster level check 1d20 + CL vs DC 11 + CL.", descriptionPtBr: "Cancela magias e efeitos mágicos. Teste 1d20 + nível vs CD 11 + nível do efeito.", classes: "Bard, Cleric, Druid, Paladin, Sorcerer, Wizard" },
  { index: "fireball-35", name: "Fireball", namePtBr: "Bola de Fogo", level: 3, school: "Evocation", castingTime: "1 action", range: "Long", duration: "Instantaneous", components: "V, S, M", description: "A ball of fire explodes in a 20-ft radius. 1d6/level fire damage (max 10d6). Reflex half.", descriptionPtBr: "Explosão de fogo em raio de 6m. 1d6/nível de dano de fogo (máx 10d6). Reflexos metade.", classes: "Sorcerer, Wizard" },
  { index: "fly-35", name: "Fly", namePtBr: "Voo", level: 3, school: "Transmutation", castingTime: "1 action", range: "Touch", duration: "1 min/level", components: "V, S, F", description: "Subject can fly at speed of 60 ft (good maneuverability).", descriptionPtBr: "Alvo voa a 18m (manobra boa). +½ nível de conjurador em Voo.", classes: "Sorcerer, Wizard" },
  { index: "haste-35", name: "Haste", namePtBr: "Velocidade", level: 3, school: "Transmutation", castingTime: "1 action", range: "Close", duration: "1 round/level", components: "V, S, M", description: "One creature/level moves faster, +1 attack, +1 AC, +1 Reflex, +30 ft speed.", descriptionPtBr: "1 criatura/nível: +1 ataque, +1 CA, +1 Reflexos, +9m deslocamento, 1 ataque extra.", classes: "Bard, Sorcerer, Wizard" },
  { index: "lightning-bolt-35", name: "Lightning Bolt", namePtBr: "Relâmpago", level: 3, school: "Evocation", castingTime: "1 action", range: "120 ft line", duration: "Instantaneous", components: "V, S, M", description: "A stroke of lightning dealing 1d6/level electricity damage (max 10d6).", descriptionPtBr: "Linha de relâmpago de 36m. 1d6/nível de dano elétrico (máx 10d6). Reflexos metade.", classes: "Sorcerer, Wizard" },
  { index: "magic-circle-against-evil-35", name: "Magic Circle against Evil", namePtBr: "Círculo Mágico contra o Mal", level: 3, school: "Abjuration", castingTime: "1 action", range: "Touch", duration: "10 min/level", components: "V, S, M/DF", description: "As protection from evil, but 10-ft radius and 10 min/level.", descriptionPtBr: "Como Proteção contra o Mal, mas raio de 3m e 10 min/nível.", classes: "Cleric, Paladin, Sorcerer, Wizard" },
  { index: "prayer-35", name: "Prayer", namePtBr: "Prece", level: 3, school: "Enchantment", castingTime: "1 action", range: "40 ft", duration: "1 round/level", components: "V, S, DF", description: "Allies get +1 luck bonus on attacks, damage, saves, skills. Enemies get -1.", descriptionPtBr: "Aliados: +1 sorte em ataques, dano, salvaguardas, perícias. Inimigos: -1.", classes: "Cleric, Paladin" },
  { index: "slow-35", name: "Slow", namePtBr: "Lentidão", level: 3, school: "Transmutation", castingTime: "1 action", range: "Close", duration: "1 round/level", components: "V, S, M", description: "One subject/level can only take a single move or standard action each turn.", descriptionPtBr: "1 alvo/nível: só uma ação padrão OU de movimento por turno. -1 CA, ataque, Reflexos.", classes: "Bard, Sorcerer, Wizard" },
  { index: "suggestion-35", name: "Suggestion", namePtBr: "Sugestão", level: 3, school: "Enchantment", castingTime: "1 action", range: "Close", duration: "1 hour/level", components: "V, M", description: "You influence the actions of the target creature by suggesting a course of activity.", descriptionPtBr: "Sugere uma atividade razoável ao alvo. Vontade nega. Segue por até 1 hora/nível.", classes: "Bard, Sorcerer, Wizard" },
];

// ── Execução ──────────────────────────────

async function importSpells35() {
  console.log("🔮 Importando magias SRD 3.5 (PT-BR primeiro)...\n");
  let created = 0, skipped = 0;

  for (const s of SPELLS_35) {
    const existing = await prisma.srdSpell.findUnique({ where: { index: s.index } });
    if (existing) { skipped++; continue; }

    await prisma.srdSpell.create({
      data: {
        index: s.index, name: s.name, namePtBr: s.namePtBr,
        edition: "3.5", level: s.level, school: s.school,
        castingTime: s.castingTime, range: s.range, duration: s.duration,
        components: s.components, concentration: s.duration.includes("Concentration"),
        description: s.description, descriptionPtBr: s.descriptionPtBr,
        classes: s.classes, source: "SRD 3.5",
      },
    });
    created++;
  }

  console.log(`📖 Magias 3.5: ${created} criadas, ${skipped} já existiam (total: ${SPELLS_35.length})`);
}

async function main() {
  await importSpells35();
  const t35 = await prisma.srdSpell.count({ where: { edition: "3.5" } });
  const t5e = await prisma.srdSpell.count({ where: { edition: "5e" } });
  console.log(`\n📊 Magias no banco: ${t35} (3.5) + ${t5e} (5e) = ${t35 + t5e} total`);
  console.log("✅ Importação concluída!");
}

main()
  .catch((e) => { console.error("Erro:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
