// ══════════════════════════════════════════════════════
// Equipamentos 3.5 — Traduções hardcoded PT-BR
// ══════════════════════════════════════════════════════

export const equipmentNames35: Record<string, string> = {
  // Ácidos e Alquímicos
  "acid-35": "Ácido",
  "alchemist-s-fire-35": "Fogo Alquímico",
  "alchemist-s-lab-35": "Laboratório de Alquimista",
  "antitoxin-35": "Antitoxina",
  "smokestick-35": "Bastão de Fumaça",
  "sunrod-35": "Bastão Solar",
  "tanglefoot-bag-35": "Bolsa de Cola",
  "thunderstone-35": "Pedra-Trovão",
  "tindertwig-35": "Graveto de Fósforo",
  "holy-water-35": "Água Benta",

  // Armas
  "arrow-35": "Flecha",
  "bastard-sword-35": "Espada Bastarda",
  "battleaxe-35": "Machado de Batalha",
  "bayonet-35": "Baioneta",
  "blowgun-35": "Zarabatana",
  "blowgun-darts-10-35": "Dardos de Zarabatana (10)",
  "bolas-35": "Boleadeira",
  "club-35": "Clava",
  "composite-longbow-1-35": "Arco Longo Composto (+1)",
  "composite-longbow-2-35": "Arco Longo Composto (+2)",
  "composite-longbow-3-35": "Arco Longo Composto (+3)",
  "composite-longbow-4-35": "Arco Longo Composto (+4)",
  "composite-shortbow-1-35": "Arco Curto Composto (+1)",
  "composite-shortbow-2-35": "Arco Curto Composto (+2)",
  "composite-shortbow-3-35": "Arco Curto Composto (+3)",
  "composite-shortbow-4-35": "Arco Curto Composto (+4)",
  "crossbow-bolt-35": "Virote de Besta",
  "dagger-35": "Adaga",
  "dart-35": "Dardo",
  "dire-flail-35": "Mangual Atroz",
  "dwarven-urgrosh-35": "Urgrosh Anão",
  "dwarven-waraxe-35": "Machado de Guerra Anão",
  "falchion-35": "Falcião",
  "flail-35": "Mangual",
  "gauntlet-35": "Manopla",
  "glaive-35": "Glaive",
  "gnome-hooked-hammer-35": "Martelo Gancho Gnômico",
  "greataxe-35": "Machado Grande",
  "greatclub-35": "Clava Grande",
  "greatsword-35": "Espada Grande",
  "guisarme-35": "Guisarme",
  "halberd-35": "Alabarda",
  "hand-crossbow-35": "Besta de Mão",
  "handaxe-35": "Machadinha",
  "heavy-crossbow-35": "Besta Pesada",
  "heavy-flail-35": "Mangual Pesado",
  "heavy-mace-35": "Maça Pesada",
  "heavy-pick-35": "Picareta Pesada",
  "heavy-repeating-crossbow-35": "Besta de Repetição Pesada",
  "javelin-35": "Dardo de Arremesso",
  "kama-35": "Kama",
  "kukri-35": "Kukri",
  "lance-35": "Lança de Montaria",
  "light-crossbow-35": "Besta Leve",
  "light-hammer-35": "Martelo Leve",
  "light-mace-35": "Maça Leve",
  "light-pick-35": "Picareta Leve",
  "light-repeating-crossbow-35": "Besta de Repetição Leve",
  "longbow-35": "Arco Longo",
  "longspear-35": "Lança Longa",
  "longsword-35": "Espada Longa",
  "morningstar-35": "Estrela d'Alva",
  "net-35": "Rede",
  "nunchaku-35": "Nunchaku",
  "orc-double-axe-35": "Machado Duplo Orc",
  "punching-dagger-35": "Adaga de Soco",
  "quarterstaff-35": "Bordão",
  "ranseur-35": "Ranseur",
  "rapier-35": "Rapieira",
  "repeating-crossbow-bolt-35": "Virote de Besta de Repetição",
  "sai-35": "Sai",
  "sap-35": "Porrete",
  "scimitar-35": "Cimitarra",
  "scythe-35": "Foice",
  "shortbow-35": "Arco Curto",
  "shortspear-35": "Lança Curta",
  "shortsword-35": "Espada Curta",
  "sickle-35": "Foicinha",
  "sling-35": "Funda",
  "sling-bullet-35": "Projétil de Funda",
  "spiked-chain-35": "Corrente com Espinhos",
  "throwing-axe-35": "Machado de Arremesso",
  "trident-35": "Tridente",
  "two-bladed-sword-35": "Espada de Duas Lâminas",
  "war-hammer-35": "Martelo de Guerra",
  "whip-35": "Chicote",
  "armor-spikes-35": "Espinhos de Armadura",
  "shield-spikes-heavy-35": "Espinhos de Escudo (Pesado)",
  "shield-spikes-light-35": "Espinhos de Escudo (Leve)",
  "hammer-35": "Martelo",

  // Armaduras
  "banded-mail-35": "Cota de Talas",
  "breastplate-35": "Peitoral",
  "buckler-35": "Broquel",
  "chain-shirt-35": "Camisão de Malha",
  "chainmail-35": "Cota de Malha",
  "full-plate-35": "Placa Completa",
  "half-plate-35": "Meia-Placa",
  "heavy-steel-shield-35": "Escudo de Aço Pesado",
  "heavy-wooden-shield-35": "Escudo de Madeira Pesado",
  "hide-armor-35": "Armadura de Couro Curtido",
  "leather-armor-35": "Armadura de Couro",
  "light-steel-shield-35": "Escudo de Aço Leve",
  "light-wooden-shield-35": "Escudo de Madeira Leve",
  "padded-armor-35": "Armadura Acolchoada",
  "scale-mail-35": "Brunea",
  "splint-mail-35": "Cota de Talas Reforçada",
  "studded-leather-35": "Couro Batido",
  "tower-shield-35": "Escudo Torre",
  "barding-large-creature-35": "Barda, Criatura Grande",
  "barding-medium-creature-35": "Barda, Criatura Média",

  // Roupas
  "artisan-s-outfit-35": "Traje de Artesão",
  "cleric-s-vestments-35": "Vestimentas de Clérigo",
  "cold-weather-outfit-35": "Traje de Clima Frio",
  "courtier-s-outfit-35": "Traje de Cortesão",
  "entertainer-s-outfit-35": "Traje de Artista",
  "explorer-s-outfit-35": "Traje de Explorador",
  "monk-s-outfit-35": "Traje de Monge",
  "noble-s-outfit-35": "Traje de Nobre",
  "peasant-s-outfit-35": "Traje de Camponês",
  "royal-outfit-35": "Traje Real",
  "scholar-s-outfit-35": "Traje de Estudioso",
  "traveler-s-outfit-35": "Traje de Viajante",

  // Kits e Ferramentas
  "artisan-s-tools-35": "Ferramentas de Artesão",
  "artisan-s-tools-masterworked-35": "Ferramentas de Artesão (Obra-prima)",
  "climber-s-kit-35": "Kit de Escalada",
  "disguise-kit-35": "Kit de Disfarce",
  "healer-s-kit-35": "Kit de Cura",
  "musical-instrument-common-35": "Instrumento Musical (Comum)",
  "musical-instrument-masterworked-35": "Instrumento Musical (Obra-prima)",
  "thieves-tools-35": "Ferramentas de Ladrão",
  "thieves-tools-masterwork-35": "Ferramentas de Ladrão (Obra-prima)",
  "spell-component-pouch-35": "Bolsa de Componentes",
  "pouch-spell-component-35": "Bolsa de Componentes",

  // Equipamento Geral
  "backpack-common-35": "Mochila (Comum)",
  "backpack-masterwork-35": "Mochila (Obra-prima)",
  "barrel-35": "Barril",
  "basket-35": "Cesta",
  "bedroll-35": "Saco de Dormir",
  "bell-35": "Sino",
  "bit-and-bridle-35": "Freio e Bridão",
  "blanket-winter-35": "Cobertor de Inverno",
  "block-and-tackle-35": "Roldana",
  "bottle-wine-glass-35": "Garrafa de Vinho (Vidro)",
  "bucket-35": "Balde",
  "caltrops-35": "Estrepes",
  "candle-35": "Vela",
  "canvas-35": "Lona",
  "case-map-or-scroll-35": "Estojo de Mapa/Pergaminho",
  "chain-10-ft-35": "Corrente (3m)",
  "chalk-35": "Giz",
  "chest-35": "Baú",
  "crowbar-35": "Pé de Cabra",
  "feed-35": "Ração Animal",
  "firewood-35": "Lenha",
  "fishhook-35": "Anzol",
  "fishing-net-25-sq-ft-35": "Rede de Pesca (25 pés²)",
  "flask-35": "Frasco",
  "flint-and-steel-35": "Pederneira",
  "grappling-hook-35": "Gancho de Escalada",
  "holly-and-mistletoe-35": "Azevinho e Visco",
  "holy-symbol-silver-35": "Símbolo Sagrado (Prata)",
  "holy-symbol-wooden-35": "Símbolo Sagrado (Madeira)",
  "hooded-lantern-35": "Lanterna do Capuz",
  "hourglass-35": "Ampulheta",
  "ink-1-oz-vial-35": "Tinta (1 oz)",
  "inkpen-35": "Caneta-Tinteiro",
  "jug-clay-35": "Jarro (Argila)",
  "ladder-10-foot-35": "Escada (3m)",
  "lamp-common-35": "Lamparina",
  "lantern-bullseye-35": "Lanterna Direcionada",
  "lock-amazing-35": "Fechadura (Incrível)",
  "lock-average-35": "Fechadura (Comum)",
  "lock-good-35": "Fechadura (Boa)",
  "lock-very-simple-35": "Fechadura (Muito Simples)",
  "magnifying-glass-35": "Lupa",
  "manacles-35": "Algemas",
  "manacles-masterworked-35": "Algemas (Obra-prima)",
  "mirror-small-steel-35": "Espelho (Aço Pequeno)",
  "mug-tankard-clay-35": "Caneca (Argila)",
  "oil-1-pint-flask-35": "Óleo (Frasco)",
  "paper-35": "Papel",
  "parchment-35": "Pergaminho",
  "pick-miner-s-35": "Picareta de Minerador",
  "pitcher-clay-35": "Jarra (Argila)",
  "piton-35": "Piton",
  "pole-10-foot-35": "Vara (3m)",
  "pot-iron-35": "Panela (Ferro)",
  "pouch-belt-35": "Bolsa de Cinto",
  "ram-portable-35": "Aríete Portátil",
  "rations-trail-35": "Rações de Viagem",
  "rope-hempen-1m-35": "Corda de Cânhamo (1m)",
  "rope-silk-1m-35": "Corda de Seda (1m)",
  "sack-35": "Saco",
  "scale-merchant-s-35": "Balança de Mercador",
  "sealing-wax-35": "Lacre",
  "sewing-needle-35": "Agulha de Costura",
  "signal-whistle-35": "Apito de Sinalização",
  "signet-ring-35": "Anel Sinete",
  "sledge-35": "Marreta",
  "soap-35": "Sabão",
  "spade-or-shovel-35": "Pá ou Enxada",
  "spyglass-35": "Luneta",
  "tent-35": "Tenda",
  "torch-35": "Tocha",
  "vial-35": "Frasco Pequeno",
  "waterskin-35": "Cantil",
  "whetstone-35": "Pedra de Amolar",
  "water-clock-35": "Relógio d'Água",

  // Selas e Montarias
  "saddle-military-35": "Sela Militar",
  "saddle-pack-35": "Sela de Carga",
  "saddle-riding-35": "Sela de Montaria",
  "exotic-saddle-military-35": "Sela Exótica Militar",
  "exotic-saddle-pack-35": "Sela Exótica de Carga",
  "exotic-saddle-riding-35": "Sela Exótica de Montaria",
  "saddlebags-35": "Alforjes",

  // Montarias / Animais
  "dog-guard-35": "Cão de Guarda",
  "dog-riding-35": "Cão de Montaria",
  "donkey-or-mule-35": "Burro ou Mula",
  "horse-heavy-35": "Cavalo Pesado",
  "horse-light-35": "Cavalo Leve",
  "pony-35": "Pônei",
  "warhorse-heavy-35": "Cavalo de Guerra Pesado",
  "warhorse-light-35": "Cavalo de Guerra Leve",
  "warpony-35": "Pônei de Guerra",
};
