// Traduções PT-BR de Features de Classe (5e)
// Tradução por nome (não index) pois o mesmo nome é reutilizado em múltiplas classes
export const featureNames: Record<string, string> = {
  "Ability Score Improvement": "Aumento de Atributo",
  "Action Surge (1 use)": "Surto de Ação (1 uso)",
  "Action Surge (2 uses)": "Surto de Ação (2 usos)",
  "Additional Fighting Style": "Estilo de Combate Adicional",
  "Additional Magical Secrets": "Segredos Mágicos Adicionais",
  "Arcane Recovery": "Recuperação Arcana",
  "Arcane Tradition": "Tradição Arcana",
  "Arcane Tradition feature": "Feature de Tradição Arcana",
  "Archdruid": "Arquidruida",
  "Aura improvements": "Melhorias de Aura",
  "Aura of Courage": "Aura de Coragem",
  "Aura of Devotion": "Aura de Devoção",
  "Aura of Protection": "Aura de Proteção",
  "Bard College": "Colégio de Bardo",
  "Bard College feature": "Feature de Colégio de Bardo",
  "Bardic Inspiration (d10)": "Inspiração de Bardo (d10)",
  "Bardic Inspiration (d12)": "Inspiração de Bardo (d12)",
  "Bardic Inspiration (d6)": "Inspiração de Bardo (d6)",
  "Bardic Inspiration (d8)": "Inspiração de Bardo (d8)",
  "Beast Spells": "Magias Bestiais",
  "Blessed Healer": "Curandeiro Abençoado",
  "Blindsense": "Sentido Cego",
  "Bonus Cantrip": "Truque Bônus",
  "Bonus Proficiencies": "Proficiências Bônus",
  "Bonus Proficiency": "Proficiência Bônus",
  "Brutal Critical (1 die)": "Crítico Brutal (1 dado)",
  "Brutal Critical (2 dice)": "Crítico Brutal (2 dados)",
  "Brutal Critical (3 dice)": "Crítico Brutal (3 dados)",
  "Channel Divinity": "Canalizar Divindade",
  "Channel Divinity (1/rest)": "Canalizar Divindade (1/descanso)",
  "Channel Divinity (2/rest)": "Canalizar Divindade (2/descanso)",
  "Channel Divinity (3/rest)": "Canalizar Divindade (3/descanso)",
  "Channel Divinity: Preserve Life": "Canalizar Divindade: Preservar a Vida",
  "Channel Divinity: Sacred Weapon": "Canalizar Divindade: Arma Sagrada",
  "Channel Divinity: Turn the Unholy": "Canalizar Divindade: Expulsar o Profano",
  "Channel Divinity: Turn Undead": "Canalizar Divindade: Expulsar Mortos-Vivos",
  "Circle of the Land": "Círculo da Terra",
  "Circle of the Land: Arctic": "Círculo da Terra: Ártico",
  "Circle of the Land: Coast": "Círculo da Terra: Costa",
  "Circle of the Land: Desert": "Círculo da Terra: Deserto",
  "Circle of the Land: Forest": "Círculo da Terra: Floresta",
  "Circle of the Land: Grassland": "Círculo da Terra: Planície",
  "Circle of the Land: Mountain": "Círculo da Terra: Montanha",
  "Circle of the Land: Swamp": "Círculo da Terra: Pântano",
  "Circle Spells": "Magias do Círculo",
  "Cleansing Touch": "Toque Purificador",
  "Countercharm": "Contrafeitiço",
  "Cunning Action": "Ação Ardilosa",
  "Cutting Words": "Palavras Cortantes",
  "Danger Sense": "Sentido de Perigo",
  "Dark One's Blessing": "Bênção do Sombrio",
  "Dark One's Own Luck": "Sorte do Sombrio",
  "Defensive Tactics": "Táticas Defensivas",
  "Defensive Tactics: Escape the Horde": "Táticas Defensivas: Escapar da Horda",
  "Defensive Tactics: Multiattack Defense": "Táticas Defensivas: Defesa contra Ataques Múltiplos",
  "Defensive Tactics: Steel Will": "Táticas Defensivas: Vontade de Aço",
  "Deflect Missiles": "Defletir Projéteis",
  "Destroy Undead (CR 1 or below)": "Destruir Mortos-Vivos (ND 1 ou menor)",
  "Destroy Undead (CR 1/2 or below)": "Destruir Mortos-Vivos (ND 1/2 ou menor)",
  "Destroy Undead (CR 2 or below)": "Destruir Mortos-Vivos (ND 2 ou menor)",
  "Destroy Undead (CR 3 or below)": "Destruir Mortos-Vivos (ND 3 ou menor)",
  "Destroy Undead (CR 4 or below)": "Destruir Mortos-Vivos (ND 4 ou menor)",
  "Diamond Soul": "Alma de Diamante",
  "Disciple of Life": "Discípulo da Vida",
  "Divine Domain": "Domínio Divino",
  "Divine Domain feature": "Feature de Domínio Divino",
  "Divine Health": "Saúde Divina",
  "Divine Intervention": "Intervenção Divina",
  "Divine Intervention Improvement": "Melhoria de Intervenção Divina",
  "Divine Sense": "Sentido Divino",
  "Divine Smite": "Destruição Divina",
  "Divine Strike": "Golpe Divino",
  "Domain Spells": "Magias de Domínio",
  "Draconic Presence": "Presença Dracônica",
  "Draconic Resilience": "Resiliência Dracônica",
  "Dragon Ancestor": "Ancestral Dracônico",
  "Dragon Ancestor: Black - Acid Damage": "Ancestral Dracônico: Negro — Dano Ácido",
  "Dragon Ancestor: Blue - Lightning Damage": "Ancestral Dracônico: Azul — Dano Elétrico",
  "Dragon Ancestor: Brass - Fire Damage": "Ancestral Dracônico: Latão — Dano de Fogo",
  "Dragon Ancestor: Bronze - Lightning Damage": "Ancestral Dracônico: Bronze — Dano Elétrico",
  "Dragon Ancestor: Copper - Acid Damage": "Ancestral Dracônico: Cobre — Dano Ácido",
  "Dragon Ancestor: Gold - Fire Damage": "Ancestral Dracônico: Ouro — Dano de Fogo",
  "Dragon Ancestor: Green - Poison Damage": "Ancestral Dracônico: Verde — Dano de Veneno",
  "Dragon Ancestor: Red - Fire Damage": "Ancestral Dracônico: Vermelho — Dano de Fogo",
  "Dragon Ancestor: Silver - Cold Damage": "Ancestral Dracônico: Prata — Dano de Frio",
  "Dragon Ancestor: White - Cold Damage": "Ancestral Dracônico: Branco — Dano de Frio",
  "Dragon Wings": "Asas Dracônicas",
  "Druid Circle": "Círculo Druídico",
  "Druid Circle feature": "Feature de Círculo Druídico",
  "Druidic": "Druídico",
  "Eldritch Invocation: Agonizing Blast": "Invocação Mística: Explosão Agonizante",
  "Eldritch Invocation: Armor of Shadows": "Invocação Mística: Armadura das Sombras",
  "Eldritch Invocation: Ascendant Step": "Invocação Mística: Passo Ascendente",
  "Eldritch Invocation: Beast Speech": "Invocação Mística: Fala Bestial",
  "Eldritch Invocation: Beguiling Influence": "Invocação Mística: Influência Sedutora",
  "Eldritch Invocation: Bewitching Whispers": "Invocação Mística: Sussurros Encantadores",
  "Eldritch Invocation: Book of Ancient Secrets": "Invocação Mística: Livro de Segredos Ancestrais",
  "Eldritch Invocation: Chains of Carceri": "Invocação Mística: Correntes de Carceri",
  "Eldritch Invocation: Devil's Sight": "Invocação Mística: Visão do Diabo",
  "Eldritch Invocation: Dreadful Word": "Invocação Mística: Palavra Terrível",
  "Eldritch Invocation: Eldritch Sight": "Invocação Mística: Visão Mística",
  "Eldritch Invocation: Eldritch Spear": "Invocação Mística: Lança Mística",
  "Eldritch Invocation: Eyes of the Rune Keeper": "Invocação Mística: Olhos do Portador de Runas",
  "Eldritch Invocation: Fiendish Vigor": "Invocação Mística: Vigor Demoníaco",
  "Eldritch Invocation: Gaze of Two Minds": "Invocação Mística: Olhar de Duas Mentes",
  "Eldritch Invocation: Lifedrinker": "Invocação Mística: Bebedor de Vida",
  "Eldritch Invocation: Mask of Many Faces": "Invocação Mística: Máscara de Muitas Faces",
  "Eldritch Invocation: Master of Myriad Forms": "Invocação Mística: Mestre de Miríade de Formas",
  "Eldritch Invocation: Minions of Chaos": "Invocação Mística: Lacaios do Caos",
  "Eldritch Invocation: Mire the Mind": "Invocação Mística: Enlamear a Mente",
  "Eldritch Invocation: Misty Visions": "Invocação Mística: Visões Nebulosas",
  "Eldritch Invocation: One with Shadows": "Invocação Mística: Um com as Sombras",
  "Eldritch Invocation: Otherworldly Leap": "Invocação Mística: Salto Transcendental",
  "Eldritch Invocation: Repelling Blast": "Invocação Mística: Explosão Repulsora",
  "Eldritch Invocation: Sculptor of Flesh": "Invocação Mística: Escultor de Carne",
  "Eldritch Invocation: Sign of Ill Omen": "Invocação Mística: Sinal de Mau Presságio",
  "Eldritch Invocation: Thief of Five Fates": "Invocação Mística: Ladrão de Cinco Destinos",
  "Eldritch Invocation: Thirsting Blade": "Invocação Mística: Lâmina Sedenta",
  "Eldritch Invocation: Visions of Distant Realms": "Invocação Mística: Visões de Reinos Distantes",
  "Eldritch Invocation: Voice of the Chain Master": "Invocação Mística: Voz do Mestre da Corrente",
  "Eldritch Invocation: Whispers of the Grave": "Invocação Mística: Sussurros da Sepultura",
  "Eldritch Invocation: Witch Sight": "Invocação Mística: Visão da Bruxa",
  "Eldritch Invocations": "Invocações Místicas",
  "Eldritch Master": "Mestre Místico",
  "Elemental Affinity": "Afinidade Elemental",
  "Elusive": "Elusivo",
  "Empowered Evocation": "Evocação Potencializada",
  "Empty Body": "Corpo Vazio",
  "Evasion": "Evasão",
  "Evocation Savant": "Especialista em Evocação",
  "Expertise": "Especialização",
  "Extra Attack": "Ataque Extra",
  "Extra Attack (2)": "Ataque Extra (2)",
  "Extra Attack (3)": "Ataque Extra (3)",
  "Fast Hands": "Mãos Rápidas",
  "Fast Movement": "Movimento Rápido",
  "Favored Enemy (1 type)": "Inimigo Favorito (1 tipo)",
  "Favored Enemy (2 types)": "Inimigo Favorito (2 tipos)",
  "Favored Enemy (3 enemies)": "Inimigo Favorito (3 inimigos)",
  "Feral Instinct": "Instinto Selvagem",
  "Feral Senses": "Sentidos Selvagens",
  "Fiendish Resilience": "Resiliência Demoníaca",
  "Fighting Style": "Estilo de Combate",
  "Fighting Style: Archery": "Estilo de Combate: Arquearia",
  "Fighting Style: Defense": "Estilo de Combate: Defesa",
  "Fighting Style: Dueling": "Estilo de Combate: Duelismo",
  "Fighting Style: Great Weapon Fighting": "Estilo de Combate: Arma Grande",
  "Fighting Style: Protection": "Estilo de Combate: Proteção",
  "Fighting Style: Two-Weapon Fighting": "Estilo de Combate: Duas Armas",
  "Flexible Casting: Converting Spell Slot": "Conjuração Flexível: Converter Espaço de Magia",
  "Flexible Casting: Creating Spell Slots": "Conjuração Flexível: Criar Espaços de Magia",
  "Flurry of Blows": "Rajada de Golpes",
  "Foe Slayer": "Matador de Inimigos",
  "Font of Inspiration": "Fonte de Inspiração",
  "Font of Magic": "Fonte de Magia",
  "Frenzy": "Frenesi",
  "Hide in Plain Sight": "Esconder-se à Vista",
  "Holy Nimbus": "Nimbo Sagrado",
  "Hunter's Prey": "Presa do Caçador",
  "Hunter's Prey: Colossus Slayer": "Presa do Caçador: Matador de Colosso",
  "Hunter's Prey: Giant Killer": "Presa do Caçador: Matador de Gigantes",
  "Hunter's Prey: Horde Breaker": "Presa do Caçador: Destruidor de Hordas",
  "Hurl Through Hell": "Arremessar ao Inferno",
  "Improved Critical": "Crítico Aprimorado",
  "Improved Divine Smite": "Destruição Divina Aprimorada",
  "Indomitable (1 use)": "Indomável (1 uso)",
  "Indomitable (2 uses)": "Indomável (2 usos)",
  "Indomitable (3 uses)": "Indomável (3 usos)",
  "Indomitable Might": "Poder Indomável",
  "Intimidating Presence": "Presença Intimidadora",
  "Jack of All Trades": "Pau pra Toda Obra",
  "Ki": "Ki",
  "Ki Empowered Strikes": "Golpes Potencializados por Ki",
  "Land's Stride": "Passada da Terra",
  "Lay on Hands": "Imposição de Mãos",
  "Magical Secrets": "Segredos Mágicos",
  "Martial Archetype": "Arquétipo Marcial",
  "Martial Archetype feature": "Feature de Arquétipo Marcial",
  "Martial Arts": "Artes Marciais",
  "Metamagic": "Metamagia",
  "Metamagic: Careful Spell": "Metamagia: Magia Cuidadosa",
  "Metamagic: Distant Spell": "Metamagia: Magia Distante",
  "Metamagic: Empowered Spell": "Metamagia: Magia Potencializada",
  "Metamagic: Extended Spell": "Metamagia: Magia Estendida",
  "Metamagic: Heightened Spell": "Metamagia: Magia Elevada",
  "Metamagic: Quickened Spell": "Metamagia: Magia Acelerada",
  "Metamagic: Subtle Spell": "Metamagia: Magia Sutil",
  "Metamagic: Twinned Spell": "Metamagia: Magia Gêmea",
  "Mindless Rage": "Fúria Irracional",
  "Monastic Tradition": "Tradição Monástica",
  "Monastic Tradition feature": "Feature de Tradição Monástica",
  "Multiattack": "Ataque Múltiplo",
  "Multiattack: Volley": "Ataque Múltiplo: Rajada",
  "Multiattack: Whirlwind Attack": "Ataque Múltiplo: Ataque Rodopiante",
  "Mystic Arcanum (6th level)": "Arcano Místico (6º nível)",
  "Mystic Arcanum (7th level)": "Arcano Místico (7º nível)",
  "Mystic Arcanum (8th level)": "Arcano Místico (8º nível)",
  "Mystic Arcanum (9th level)": "Arcano Místico (9º nível)",
  "Natural Explorer (1 terrain type)": "Explorador Natural (1 tipo de terreno)",
  "Natural Explorer (2 terrain types)": "Explorador Natural (2 tipos de terreno)",
  "Natural Explorer (3 terrain types)": "Explorador Natural (3 tipos de terreno)",
  "Natural Recovery": "Recuperação Natural",
  "Nature's Sanctuary": "Santuário da Natureza",
  "Nature's Ward": "Proteção da Natureza",
  "Oath Spells": "Magias do Juramento",
  "Open Hand Technique": "Técnica da Mão Aberta",
  "Otherworldly Patron": "Patrono Transcendental",
  "Otherworldly Patron feature": "Feature de Patrono Transcendental",
  "Overchannel": "Sobrecarregar",
  "Pact Boon": "Dádiva do Pacto",
  "Pact Magic": "Magia de Pacto",
  "Pact of the Blade": "Pacto da Lâmina",
  "Pact of the Chain": "Pacto da Corrente",
  "Pact of the Tome": "Pacto do Tomo",
  "Path feature": "Feature de Caminho",
  "Patient Defense": "Defesa Paciente",
  "Peerless Skill": "Habilidade Incomparável",
  "Perfect Self": "Ser Perfeito",
  "Persistent Rage": "Fúria Persistente",
  "Potent Cantrip": "Truque Potente",
  "Primal Champion": "Campeão Primitivo",
  "Primal Path": "Caminho Primitivo",
  "Primeval Awareness": "Consciência Primitiva",
  "Purity of Body": "Pureza do Corpo",
  "Purity of Spirit": "Pureza do Espírito",
  "Quivering Palm": "Palma Estremecedora",
  "Rage": "Fúria",
  "Ranger Archetype": "Arquétipo de Patrulheiro",
  "Ranger Archetype feature": "Feature de Arquétipo de Patrulheiro",
  "Reckless Attack": "Ataque Imprudente",
  "Relentless Rage": "Fúria Implacável",
  "Reliable Talent": "Talento Confiável",
  "Remarkable Athlete": "Atleta Notável",
  "Retaliation": "Retaliação",
  "Roguish Archetype": "Arquétipo de Ladino",
  "Roguish Archetype feature": "Feature de Arquétipo de Ladino",
  "Sacred Oath": "Juramento Sagrado",
  "Sacred Oath feature": "Feature de Juramento Sagrado",
  "Sculpt Spells": "Esculpir Magias",
  "Second Wind": "Fôlego",
  "Second-Story Work": "Trabalho de Segundo Andar",
  "Signature Spell": "Magia Assinatura",
  "Slippery Mind": "Mente Escorregadia",
  "Slow Fall": "Queda Suave",
  "Sneak Attack": "Ataque Furtivo",
  "Song of Rest (d10)": "Canção de Descanso (d10)",
  "Song of Rest (d12)": "Canção de Descanso (d12)",
  "Song of Rest (d6)": "Canção de Descanso (d6)",
  "Song of Rest (d8)": "Canção de Descanso (d8)",
  "Sorcerous Origin": "Origem Arcana",
  "Sorcerous Origin feature": "Feature de Origem Arcana",
  "Sorcerous Restoration": "Restauração Arcana",
  "Spell Mastery": "Mestria em Magia",
  "Spellcasting: Bard": "Conjuração: Bardo",
  "Spellcasting: Cleric": "Conjuração: Clérigo",
  "Spellcasting: Druid": "Conjuração: Druida",
  "Spellcasting: Paladin": "Conjuração: Paladino",
  "Spellcasting: Ranger": "Conjuração: Patrulheiro",
  "Spellcasting: Sorcerer": "Conjuração: Feiticeiro",
  "Spellcasting: Wizard": "Conjuração: Mago",
  "Step of the Wind": "Passo do Vento",
  "Stillness of Mind": "Tranquilidade da Mente",
  "Stroke of Luck": "Golpe de Sorte",
  "Stunning Strike": "Golpe Atordoante",
  "Superior Critical": "Crítico Superior",
  "Superior Hunter's Defense": "Defesa Superior do Caçador",
  "Superior Hunter's Defense: Evasion": "Defesa Superior do Caçador: Evasão",
  "Superior Hunter's Defense: Stand Against the Tide": "Defesa Superior do Caçador: Resistir à Maré",
  "Superior Hunter's Defense: Uncanny Dodge": "Defesa Superior do Caçador: Esquiva Sobrenatural",
  "Superior Inspiration": "Inspiração Superior",
  "Supreme Healing": "Cura Suprema",
  "Supreme Sneak": "Furtividade Suprema",
  "Survivor": "Sobrevivente",
  "Thief's Reflexes": "Reflexos de Ladrão",
  "Thieves' Cant": "Gíria de Ladrão",
  "Timeless Body": "Corpo Atemporal",
  "Tongue of the Sun and Moon": "Língua do Sol e da Lua",
  "Tranquility": "Tranquilidade",
  "Unarmored Defense": "Defesa sem Armadura",
  "Unarmored Movement": "Movimento sem Armadura",
  "Uncanny Dodge": "Esquiva Sobrenatural",
  "Use Magic Device": "Usar Dispositivo Mágico",
  "Vanish": "Desaparecer",
  "Wholeness of Body": "Plenitude do Corpo",
  "Wild Shape (CR 1 or below)": "Forma Selvagem (ND 1 ou menor)",
  "Wild Shape (CR 1/2 or below, no flying speed)": "Forma Selvagem (ND 1/2 ou menor, sem voo)",
  "Wild Shape (CR 1/4 or below, no flying or swim speed)": "Forma Selvagem (ND 1/4 ou menor, sem voo ou natação)",
};
