// ══════════════════════════════════════════════════════
// Feats 3.5 — Traduções hardcoded PT-BR
// Cobre feats épicos, psiônicos e de combate do 3.5
// ══════════════════════════════════════════════════════

export const featNames35: Record<string, string> = {
  // A
  "ability-focus-35": "Foco em Habilidade",
  "additional-magic-item-space-35": "Espaço Adicional de Item Mágico",
  "aligned-attack-35": "Ataque Alinhado",
  "antipsionic-magic-35": "Magia Antipsiônica",
  "armor-skin-35": "Pele de Armadura",
  "augmented-alchemy-35": "Alquimia Aumentada",
  "automatic-quicken-spell-35": "Magia Acelerada Automática",
  "automatic-silent-spell-35": "Magia Silenciosa Automática",
  "automatic-still-spell-35": "Magia Imóvel Automática",
  "autonomous-35": "Autônomo",
  "awesome-blow-35": "Golpe Incrível",

  // B
  "bane-of-enemies-35": "Flagelo dos Inimigos",
  "blinding-speed-35": "Velocidade Ofuscante",
  "blindsight-5-ft-radius-35": "Percepção Cega (1,5m de raio)",
  "body-fuel-35": "Combustível Corporal",
  "bonus-domain-35": "Domínio Bônus",
  "boost-construct-35": "Aprimorar Construto",
  "bulwark-of-defense-35": "Baluarte de Defesa",
  "burrowing-power-35": "Poder Perfurante",

  // C
  "chain-power-35": "Poder em Cadeia",
  "chaotic-mind-35": "Mente Caótica",
  "chaotic-rage-35": "Fúria Caótica",
  "cloak-dance-35": "Dança do Manto",
  "closed-mind-35": "Mente Fechada",
  "colossal-wild-shape-35": "Forma Selvagem Colossal",
  "combat-archery-35": "Arquearia de Combate",
  "combat-manifestation-35": "Manifestação de Combate",
  "craft-cognizance-crystal-35": "Criar Cristal de Cognição",
  "craft-construct-35": "Criar Construto",
  "craft-dorje-35": "Criar Dorje",
  "craft-epic-magic-arms-and-armor-35": "Criar Armas e Armaduras Mágicas Épicas",
  "craft-epic-rod-35": "Criar Bastão Épico",
  "craft-epic-staff-35": "Criar Cajado Épico",
  "craft-epic-wondrous-item-35": "Criar Item Maravilhoso Épico",
  "craft-psicrown-35": "Criar Psicoroa",
  "craft-psionic-arms-and-armor-35": "Criar Armas e Armaduras Psiônicas",
  "craft-psionic-construct-35": "Criar Construto Psiônico",
  "craft-universal-item-35": "Criar Item Universal",

  // D
  "damage-reduction-35": "Redução de Dano",
  "deadly-precision-35": "Precisão Letal",
  "deafening-song-35": "Canção Ensurdecedora",
  "death-of-enemies-35": "Morte dos Inimigos",
  "deep-impact-35": "Impacto Profundo",
  "delay-power-35": "Retardar Poder",
  "devastating-critical-35": "Crítico Devastador",
  "dexterous-fortitude-35": "Fortitude Ágil",
  "dexterous-will-35": "Vontade Ágil",
  "diehard-35": "Teimoso",
  "diminutive-wild-shape-35": "Forma Selvagem Diminuta",
  "dire-charge-35": "Investida Atroz",
  "disguise-spell-35": "Disfarçar Magia",
  "distant-shot-35": "Tiro Distante",
  "divine-might-35": "Poder Divino",
  "divine-vengeance-35": "Vingança Divina",
  "dragon-wild-shape-35": "Forma Selvagem Dracônica",

  // E
  "efficient-item-creation-35": "Criação Eficiente de Itens",
  "empower-power-35": "Potencializar Poder",
  "empower-spell-like-ability-35": "Potencializar Habilidade Mágica",
  "energy-resistance-35": "Resistência a Energia",
  "energy-substitution-35": "Substituição de Energia",
  "enhance-spell-35": "Aprimorar Magia",
  "enlarge-power-35": "Ampliar Poder",
  "epic-dodge-35": "Esquiva Épica",
  "epic-endurance-35": "Resistência Épica",
  "epic-expanded-knowledge-35": "Conhecimento Expandido Épico",
  "epic-fortitude-35": "Fortitude Épica",
  "epic-inspiration-35": "Inspiração Épica",
  "epic-leadership-35": "Liderança Épica",
  "epic-manifestation-35": "Manifestação Épica",
  "epic-prowess-35": "Proeza Épica",
  "epic-psionic-focus-35": "Foco Psiônico Épico",
  "epic-reflexes-35": "Reflexos Épicos",
  "epic-reputation-35": "Reputação Épica",
  "epic-skill-focus-not-set-35": "Foco em Perícia Épico",
  "epic-speed-35": "Velocidade Épica",
  "epic-spell-focus-no-spell-school-selected-35": "Foco em Escola Épico",
  "epic-spell-penetration-35": "Penetração de Magia Épica",
  "epic-spellcasting-35": "Conjuração Épica",
  "epic-toughness-35": "Vitalidade Épica",
  "epic-weapon-focus-no-weapon-selected-35": "Foco em Arma Épico",
  "epic-weapon-specialization-35": "Especialização em Arma Épica",
  "epic-will-35": "Vontade Épica",
  "exceptional-deflection-35": "Deflexão Excepcional",
  "exotic-weapon-proficiency-35": "Proficiência com Arma Exótica",
  "expanded-knowledge-35": "Conhecimento Expandido",
  "extend-power-35": "Estender Poder",
  "extended-life-span-35": "Longevidade",
  "extra-music-35": "Música Extra",
  "eyes-in-the-back-of-your-head-35": "Olhos na Nuca",

  // F
  "familiar-spell-35": "Magia Familiar",
  "fast-healing-35": "Cura Acelerada",
  "fell-shot-35": "Tiro Certeiro",
  "fine-wild-shape-35": "Forma Selvagem Mínima",
  "fleet-of-foot-35": "Pés Ligeiros",
  "flyby-attack-35": "Ataque em Voo",
  "focused-sunder-35": "Destruir Focado",
  "force-of-will-35": "Força de Vontade",
  "forge-epic-ring-35": "Forjar Anel Épico",

  // G
  "gargantuan-wild-shape-35": "Forma Selvagem Imensa",
  "ghost-attack-35": "Ataque Fantasma",
  "great-charisma-35": "Grande Carisma",
  "great-constitution-35": "Grande Constituição",
  "great-dexterity-35": "Grande Destreza",
  "great-intelligence-35": "Grande Inteligência",
  "great-smiting-35": "Grande Destruição",
  "great-strength-35": "Grande Força",
  "great-wisdom-35": "Grande Sabedoria",
  "greater-manyshot-35": "Tiro Múltiplo Superior",
  "greater-multiweapon-fighting-35": "Combate com Múltiplas Armas Superior",
  "greater-power-penetration-35": "Penetração de Poder Superior",
  "greater-power-specialization-35": "Especialização em Poder Superior",
  "greater-psionic-endowment-35": "Dotação Psiônica Superior",
  "greater-psionic-fist-35": "Punho Psiônico Superior",
  "greater-psionic-shot-35": "Tiro Psiônico Superior",
  "greater-psionic-weapon-35": "Arma Psiônica Superior",
  "greater-spell-focus-no-spell-school-selected-35": "Foco em Escola Superior",
  "greater-weapon-focus-no-weapon-selected-35": "Foco em Arma Superior",
  "greater-weapon-specialization-no-weapon-selected-35": "Especialização em Arma Superior",
  "group-inspiration-35": "Inspiração em Grupo",

  // H
  "hindering-song-35": "Canção Impedidora",
  "hold-the-line-35": "Manter a Linha",
  "holy-strike-35": "Golpe Sagrado",
  "hostile-mind-35": "Mente Hostil",
  "hover-35": "Pairar",

  // I
  "ignore-material-components-35": "Ignorar Componentes Materiais",
  "imprint-stone-35": "Imprimir Pedra",
  "improved-alignment-based-casting-35": "Conjuração Baseada em Alinhamento Aprimorada",
  "improved-arrow-of-death-35": "Flecha da Morte Aprimorada",
  "improved-aura-of-courage-35": "Aura de Coragem Aprimorada",
  "improved-aura-of-despair-35": "Aura de Desespero Aprimorada",
  "improved-combat-casting-35": "Conjuração de Combate Aprimorada",
  "improved-combat-reflexes-35": "Reflexos de Combate Aprimorados",
  "improved-critical-no-weapon-selected-35": "Crítico Aprimorado",
  "improved-darkvision-35": "Visão no Escuro Aprimorada",
  "improved-death-attack-35": "Ataque Mortal Aprimorado",
  "improved-elemental-wild-shape-35": "Forma Selvagem Elemental Aprimorada",
  "improved-familiar-35": "Familiar Aprimorado",
  "improved-favored-enemy-35": "Inimigo Favorito Aprimorado",
  "improved-flyby-attack-35": "Ataque em Voo Aprimorado",
  "improved-heighten-spell-35": "Elevar Magia Aprimorado",
  "improved-ki-strike-35": "Golpe Ki Aprimorado",
  "improved-low-light-vision-35": "Visão na Penumbra Aprimorada",
  "improved-manifestation-35": "Manifestação Aprimorada",
  "improved-manyshot-35": "Tiro Múltiplo Aprimorado",
  "improved-metamagic-35": "Metamagia Aprimorada",
  "improved-metapsionics-35": "Metapsiônica Aprimorada",
  "improved-multiattack-35": "Ataque Múltiplo Aprimorado",
  "improved-multiweapon-fighting-35": "Combate com Múltiplas Armas Aprimorado",
  "improved-natural-armor-35": "Armadura Natural Aprimorada",
  "improved-natural-attack-no-weapon-set-35": "Ataque Natural Aprimorado",
  "improved-psicrystal-35": "Psicristal Aprimorado",
  "improved-sneak-attack-35": "Ataque Furtivo Aprimorado",
  "improved-spell-capacity-35": "Capacidade de Magia Aprimorada",
  "improved-spell-resistance-35": "Resistência a Magia Aprimorada",
  "improved-stunning-fist-35": "Punho Atordoante Aprimorado",
  "improved-whirlwind-attack-35": "Ataque Rodopiante Aprimorado",
  "incite-rage-35": "Incitar Fúria",
  "infinite-deflection-35": "Deflexão Infinita",
  "inquisitor-35": "Inquisidor",
  "inspire-excellence-35": "Inspirar Excelência",
  "instant-reload-35": "Recarga Instantânea",
  "intensify-spell-35": "Intensificar Magia",
  "intuitive-trapfinding-35": "Encontrar Armadilhas Intuitivo",

  // J-K
  "jack-of-all-trades-35": "Pau pra Toda Obra",
  "keen-strike-35": "Golpe Afiado",
  "knock-down-35": "Derrubar",

  // L
  "lasting-inspiration-35": "Inspiração Duradoura",
  "legendary-climber-35": "Escalador Lendário",
  "legendary-commander-35": "Comandante Lendário",
  "legendary-leaper-35": "Saltador Lendário",
  "legendary-rider-35": "Cavaleiro Lendário",
  "legendary-tracker-35": "Rastreador Lendário",
  "legendary-wrestler-35": "Lutador Lendário",
  "lingering-damage-35": "Dano Persistente",

  // M
  "magical-beast-companion-35": "Companheiro Besta Mágica",
  "magical-beast-wild-shape-35": "Forma Selvagem de Besta Mágica",
  "martial-weapon-proficiency-all-35": "Proficiência com Armas Marciais (Todas)",
  "master-staff-35": "Mestre do Cajado",
  "master-wand-35": "Mestre da Varinha",
  "maximize-power-35": "Maximizar Poder",
  "mental-leap-35": "Salto Mental",
  "mental-resistance-35": "Resistência Mental",
  "metamorphic-transfer-35": "Transferência Metamórfica",
  "mighty-rage-35": "Fúria Poderosa",
  "mind-over-body-35": "Mente sobre o Corpo",
  "mobile-defense-35": "Defesa Móvel",
  "multiattack-35": "Ataque Múltiplo",
  "multispell-35": "Multimagia",
  "multiweapon-fighting-35": "Combate com Múltiplas Armas",
  "multiweapon-rend-35": "Rasgar com Múltiplas Armas",
  "music-of-the-gods-35": "Música dos Deuses",

  // N-O
  "narrow-mind-35": "Mente Estreita",
  "negative-energy-burst-35": "Explosão de Energia Negativa",
  "open-minded-35": "Mente Aberta",
  "opportunity-power-35": "Poder de Oportunidade",
  "overchannel-35": "Sobrecarregar",
  "overwhelming-critical-35": "Crítico Avassalador",

  // P
  "penetrate-damage-reduction-35": "Penetrar Redução de Dano",
  "perfect-health-35": "Saúde Perfeita",
  "perfect-multiweapon-fighting-35": "Combate com Múltiplas Armas Perfeito",
  "perfect-two-weapon-fighting-35": "Combate com Duas Armas Perfeito",
  "permanent-emanation-35": "Emanação Permanente",
  "persistent-spell-35": "Magia Persistente",
  "planar-turning-35": "Expulsar Planar",
  "plant-control-35": "Controlar Plantas",
  "plant-defiance-35": "Desafiar Planta",
  "plant-wild-shape-35": "Forma Selvagem de Planta",
  "polyglot-35": "Poliglota",
  "positive-energy-aura-35": "Aura de Energia Positiva",
  "power-critical-35": "Poder Crítico",
  "power-knowledge-35": "Conhecimento de Poder",
  "power-penetration-35": "Penetração de Poder",
  "power-specialization-35": "Especialização em Poder",
  "psicrystal-affinity-35": "Afinidade com Psicristal",
  "psicrystal-containment-35": "Contenção de Psicristal",
  "psicrystal-power-35": "Poder do Psicristal",
  "psionic-affinity-35": "Afinidade Psiônica",
  "psionic-body-35": "Corpo Psiônico",
  "psionic-charge-35": "Investida Psiônica",
  "psionic-dodge-35": "Esquiva Psiônica",
  "psionic-endowment-35": "Dotação Psiônica",
  "psionic-fist-35": "Punho Psiônico",
  "psionic-hole-35": "Buraco Psiônico",
  "psionic-meditation-35": "Meditação Psiônica",
  "psionic-shot-35": "Tiro Psiônico",
  "psionic-talent-35": "Talento Psiônico",
  "psionic-weapon-35": "Arma Psiônica",

  // Q-R
  "quicken-power-35": "Acelerar Poder",
  "quicken-spell-like-ability-35": "Acelerar Habilidade Mágica",
  "ranged-inspiration-35": "Inspiração à Distância",
  "rapid-inspiration-35": "Inspiração Rápida",
  "rapid-metabolism-35": "Metabolismo Rápido",
  "rapid-reload-none-35": "Recarga Rápida",
  "reach-spell-35": "Magia de Alcance",
  "reactive-countersong-35": "Contra-canção Reativa",
  "reckless-offense-35": "Ofensiva Imprudente",
  "reflect-arrows-35": "Refletir Flechas",
  "repeat-spell-35": "Repetir Magia",
  "return-shot-35": "Tiro de Retorno",
  "righteous-strike-35": "Golpe Virtuoso",
  "ruinous-rage-35": "Fúria Ruinosa",

  // S
  "sacred-spell-35": "Magia Sagrada",
  "scribe-epic-scroll-35": "Escrever Pergaminho Épico",
  "scribe-tattoo-35": "Escrever Tatuagem",
  "self-concealment-35": "Auto-Ocultação",
  "sharp-shooting-35": "Tiro Preciso",
  "shattering-strike-35": "Golpe Estilhaçante",
  "sidestep-charge-35": "Esquivar Investida",
  "skill-focus-not-set-35": "Foco em Perícia",
  "snatch-35": "Agarrar",
  "sneak-attack-of-opportunity-35": "Ataque Furtivo de Oportunidade",
  "spectral-strike-35": "Golpe Espectral",
  "speed-of-thought-35": "Velocidade do Pensamento",
  "spell-focus-no-spell-school-selected-35": "Foco em Escola",
  "spell-knowledge-35": "Conhecimento de Magia",
  "spell-opportunity-35": "Oportunidade de Magia",
  "spell-stowaway-no-spell-set-35": "Clandestino de Magia",
  "spellcasting-harrier-35": "Assediador de Conjurador",
  "split-psionic-ray-35": "Dividir Raio Psiônico",
  "spontaneous-domain-access-35": "Acesso Espontâneo a Domínio",
  "spontaneous-spell-35": "Magia Espontânea",
  "stand-still-35": "Ficar Parado",
  "storm-of-throws-35": "Tempestade de Arremessos",
  "subdual-substitution-35": "Substituição de Dano",
  "superior-expertise-35": "Especialização Superior",
  "superior-initiative-35": "Iniciativa Superior",
  "swarm-of-arrows-35": "Enxame de Flechas",

  // T
  "talented-35": "Talentoso",
  "tenacious-magic-no-spell-set-35": "Magia Tenaz",
  "terrifying-rage-35": "Fúria Aterrorizante",
  "thundering-rage-35": "Fúria Trovejante",
  "tower-shield-proficiency-35": "Proficiência com Escudo Torre",
  "twin-power-35": "Poder Duplo",
  "two-weapon-rend-35": "Rasgar com Duas Armas",

  // U
  "unavoidable-strike-35": "Golpe Inevitável",
  "uncanny-accuracy-35": "Precisão Sobrenatural",
  "unconditional-power-35": "Poder Incondicional",
  "undead-mastery-35": "Maestria em Mortos-Vivos",
  "unholy-strike-35": "Golpe Profano",
  "up-the-walls-35": "Subir nas Paredes",

  // V-W
  "vermin-wild-shape-35": "Forma Selvagem de Verme",
  "vorpal-strike-35": "Golpe Vorpal",
  "weapon-focus-no-weapon-selected-35": "Foco em Arma",
  "weapon-proficiency-no-weapon-selected-35": "Proficiência com Arma",
  "weapon-specialization-no-weapon-selected-35": "Especialização em Arma",
  "widen-aura-of-courage-35": "Ampliar Aura de Coragem",
  "widen-aura-of-despair-35": "Ampliar Aura de Desespero",
  "widen-power-35": "Ampliar Poder",
  "wild-talent-35": "Talento Selvagem",
  "wingover-35": "Virada em Voo",
  "wounding-attack-35": "Ataque Sangrento",
  "zone-of-animation-35": "Zona de Animação",
};
