// Nomes PT-BR dos equipamentos do SRD 5e
export const equipmentNames: Record<string, string> = {
  "abacus": "Ábaco",
  "acid-vial": "Frasco de Ácido",
  "alchemists-fire-flask": "Frasco de Fogo Alquímico",
  "alchemists-supplies": "Suprimentos de Alquimista",
  "arrow": "Flecha",
  "backpack": "Mochila",
  "bagpipes": "Gaita de Foles",
  "ball-bearings-bag-of-1000": "Esferas de Metal (bolsa com 1000)",
  "barrel": "Barril",
  "baskethilt-dagger": "Adaga",
  "battleaxe": "Machado de Batalha",
  "bedroll": "Saco de Dormir",
  "bell": "Sino",
  "bit-and-bridle": "Freio e Rédea",
  "blanket": "Cobertor",
  "block-and-tackle": "Roldana",
  "blowgun": "Zarabatana",
  "blowgun-needle": "Agulha de Zarabatana",
  "book": "Livro",
  "bottle-glass": "Garrafa de Vidro",
  "brewers-supplies": "Suprimentos de Cervejeiro",
  "bucket": "Balde",
  "burglars-pack": "Pacote de Assaltante",
  "calligraphers-supplies": "Suprimentos de Calígrafo",
  "caltrops": "Estrepes",
  "caltrops-bag-of-20": "Estrepes (bolsa com 20)",
  "camel": "Camelo",
  "candle": "Vela",
  "carpenters-tools": "Ferramentas de Carpinteiro",
  "cartographers-tools": "Ferramentas de Cartógrafo",
  "chain-10-feet": "Corrente (3 metros)",
  "chain-mail": "Cota de Malha",
  "chain-shirt": "Camisa de Malha",
  "chalk-1-piece": "Giz (1 peça)",
  "chest": "Baú",
  "climbers-kit": "Kit de Escalada",
  "club": "Clava",
  "cobblers-tools": "Ferramentas de Sapateiro",
  "component-pouch": "Bolsa de Componentes",
  "cooks-utensils": "Utensílios de Cozinheiro",
  "crossbow-bolt": "Virote de Besta",
  "crossbow-hand": "Besta de Mão",
  "crossbow-heavy": "Besta Pesada",
  "crossbow-light": "Besta Leve",
  "crowbar": "Pé de Cabra",
  "crystal": "Cristal",
  "dagger": "Adaga",
  "dart": "Dardo",
  "dice-set": "Conjunto de Dados",
  "diplomats-pack": "Pacote de Diplomata",
  "disguise-kit": "Kit de Disfarce",
  "donkey": "Burro",
  "drum": "Tambor",
  "dulcimer": "Dulcimer",
  "dungeoneers-pack": "Pacote de Explorador",
  "elephant": "Elefante",
  "emblem": "Emblema",
  "entertainers-pack": "Pacote de Artista",
  "explorers-pack": "Pacote de Explorador",
  "fine-clothes": "Roupas Finas",
  "fishing-tackle": "Equipamento de Pesca",
  "flail": "Mangual",
  "flask-or-tankard": "Frasco ou Caneca",
  "flute": "Flauta",
  "forgery-kit": "Kit de Falsificação",
  "glaive": "Glaive",
  "glassblowers-tools": "Ferramentas de Vidreiro",
  "grappling-hook": "Gancho de Escalada",
  "greataxe": "Machado Grande",
  "greatclub": "Clava Grande",
  "greatsword": "Espada Grande",
  "halberd": "Alabarda",
  "half-plate-armor": "Meia Armadura",
  "hammer": "Martelo",
  "hammer-sledge": "Marreta",
  "handaxe": "Machadinha",
  "healers-kit": "Kit de Curandeiro",
  "herbalism-kit": "Kit de Herbalismo",
  "hide-armor": "Armadura de Couro Batido",
  "holy-water-flask": "Frasco de Água Benta",
  "horn": "Trombeta",
  "horse-draft": "Cavalo de Tração",
  "horse-riding": "Cavalo de Montaria",
  "hourglass": "Ampulheta",
  "hunting-trap": "Armadilha de Caça",
  "ink-1-ounce-bottle": "Tinta (frasco de 30ml)",
  "ink-pen": "Caneta de Tinta",
  "javelin": "Azagaia",
  "jewelers-tools": "Ferramentas de Joalheiro",
  "jug-or-pitcher": "Jarro",
  "ladder-10-foot": "Escada (3 metros)",
  "lamp": "Lamparina",
  "lance": "Lança de Montaria",
  "lantern-bullseye": "Lanterna Direcionada",
  "lantern-hooded": "Lanterna Encapuzada",
  "leather-armor": "Armadura de Couro",
  "leatherworkers-tools": "Ferramentas de Curtidor",
  "light-hammer": "Martelo Leve",
  "lock": "Fechadura",
  "longbow": "Arco Longo",
  "longsword": "Espada Longa",
  "lute": "Alaúde",
  "lyre": "Lira",
  "mace": "Maça",
  "magnifying-glass": "Lupa",
  "manacles": "Algemas",
  "masons-tools": "Ferramentas de Pedreiro",
  "maul": "Malho",
  "mess-kit": "Kit de Refeição",
  "mirror-steel": "Espelho de Aço",
  "morningstar": "Estrela d'Alva",
  "mule": "Mula",
  "navigators-tools": "Ferramentas de Navegador",
  "net": "Rede",
  "oil-flask": "Frasco de Óleo",
  "orb": "Orbe",
  "padded-armor": "Armadura Acolchoada",
  "painters-supplies": "Suprimentos de Pintor",
  "pan-flute": "Flauta de Pã",
  "paper-one-sheet": "Papel (uma folha)",
  "parchment-one-sheet": "Pergaminho (uma folha)",
  "perfume-vial": "Frasco de Perfume",
  "pick-miners": "Picareta",
  "pike": "Pique",
  "piton": "Piton",
  "plate-armor": "Armadura de Placas",
  "playing-card-set": "Baralho",
  "poisoners-kit": "Kit de Envenenador",
  "pole-10-foot": "Vara (3 metros)",
  "pony": "Pônei",
  "pot-iron": "Panela de Ferro",
  "potion-of-healing": "Poção de Cura",
  "potters-tools": "Ferramentas de Oleiro",
  "pouch": "Bolsa",
  "priests-pack": "Pacote de Sacerdote",
  "quarterstaff": "Bordão",
  "quiver": "Aljava",
  "ram-portable": "Aríete Portátil",
  "rapier": "Rapieira",
  "rations-1-day": "Rações (1 dia)",
  "reliquary": "Relicário",
  "ring-mail": "Brunea",
  "robes": "Mantos",
  "rod": "Bastão",
  "rope-hempen-50-feet": "Corda de Cânhamo (15 metros)",
  "rope-silk-50-feet": "Corda de Seda (15 metros)",
  "sack": "Saco",
  "scale-mail": "Armadura de Escamas",
  "scale-merchants": "Balança de Mercador",
  "scholars-pack": "Pacote de Estudioso",
  "scimitar": "Cimitarra",
  "sealing-wax": "Cera de Selo",
  "shawm": "Charamela",
  "shield": "Escudo",
  "shortbow": "Arco Curto",
  "shortsword": "Espada Curta",
  "shovel": "Pá",
  "sickle": "Foice",
  "signal-whistle": "Apito",
  "signet-ring": "Anel de Sinete",
  "sling": "Funda",
  "sling-bullet": "Projétil de Funda",
  "smiths-tools": "Ferramentas de Ferreiro",
  "soap": "Sabão",
  "spear": "Lança",
  "spellbook": "Grimório",
  "sprig-of-mistletoe": "Ramo de Visco",
  "splint-armor": "Armadura Segmentada",
  "spyglass": "Luneta",
  "staff": "Cajado",
  "string-10-feet": "Barbante (3 metros)",
  "studded-leather-armor": "Couro Batido Cravejado",
  "tent-two-person": "Barraca (2 pessoas)",
  "thieves-tools": "Ferramentas de Ladrão",
  "tinderbox": "Caixa de Fogo",
  "tinkers-tools": "Ferramentas de Funileiro",
  "torch": "Tocha",
  "totem": "Totem",
  "trident": "Tridente",
  "vial": "Frasco",
  "viol": "Viola",
  "wand": "Varinha",
  "war-pick": "Picareta de Guerra",
  "warhammer": "Martelo de Guerra",
  "waterskin": "Cantil",
  "weavers-tools": "Ferramentas de Tecelão",
  "whip": "Chicote",
  "woodcarvers-tools": "Ferramentas de Entalhador",
  "wooden-staff": "Cajado de Madeira",
  // Faltantes
  "alms-box": "Caixa de Esmolas",
  "amulet": "Amuleto",
  "animal-feed-1-day": "Ração Animal (1 dia)",
  "antitoxin-vial": "Antitoxina (frasco)",
  "barding-breastplate": "Barda Peitoral",
  "barding-chain-mail": "Barda de Cota de Malha",
  "barding-chain-shirt": "Barda de Camisa de Malha",
  "barding-half-plate": "Barda de Meia Armadura",
  "barding-hide": "Barda de Couro Batido",
  "barding-leather": "Barda de Couro",
  "barding-padded": "Barda Acolchoada",
  "barding-plate": "Barda de Placas",
  "barding-ring-mail": "Barda Brunea",
  "barding-scale-mail": "Barda de Escamas",
  "barding-splint": "Barda Segmentada",
  "barding-studded-leather": "Barda de Couro Cravejado",
  "basket": "Cesto",
  "block-of-incense": "Bloco de Incenso",
  "breastplate": "Peitoral",
  "carriage": "Carruagem",
  "cart": "Carroça",
  "case-crossbow-bolt": "Estojo de Virotes",
  "case-map-or-scroll": "Estojo de Mapas ou Pergaminhos",
  "chariot": "Biga",
  "clothes-common": "Roupas Comuns",
  "clothes-costume": "Fantasia",
  "clothes-fine": "Roupas Finas",
  "clothes-travelers": "Roupas de Viajante",
  "healer-s-kit": "Kit de Curandeiro",
  "hooded-lantern": "Lanterna Encapuzada",
  "keelboat": "Barco a Quilha",
  "longship": "Navio Longo",
  "monks-pack": "Pacote de Monge",
  "poison-basic-vial": "Veneno Básico (frasco)",
  "rowboat": "Barco a Remo",
  "sailing-ship": "Navio à Vela",
  "sled": "Trenó",
  "wagon": "Vagão",
  "warship": "Navio de Guerra",
  "censer": "Incensário",
  "galley": "Galera",
  "little-bag-of-sand": "Saquinho de Areia",
  "mastiff": "Mastim",
  "saddle-exotic": "Sela Exótica",
  "saddle-military": "Sela Militar",
  "saddle-pack": "Sela de Carga",
  "saddle-riding": "Sela de Montaria",
  "saddlebags": "Alforjes",
  "small-knife": "Faca Pequena",
  "spike-iron": "Estaca de Ferro",
  "stabling-1-day": "Estab. de Montaria (1 dia)",
  "vestments": "Paramentos",
  "warhorse": "Cavalo de Guerra",
  "whetstone": "Pedra de Amolar",
  "yew-wand": "Varinha de Teixo",
};

// Nomes PT-BR dos itens mágicos do SRD 5e
export const magicItemNames: Record<string, string> = {
  "adamantine-armor": "Armadura de Adamantina",
  "ammunition-1": "Munição +1",
  "ammunition-2": "Munição +2",
  "ammunition-3": "Munição +3",
  "amulet-of-health": "Amuleto de Saúde",
  "amulet-of-proof-against-detection-and-location": "Amuleto contra Detecção e Localização",
  "amulet-of-the-planes": "Amuleto dos Planos",
  "animated-shield": "Escudo Animado",
  "apparatus-of-the-crab": "Aparato do Caranguejo",
  "armor-1": "Armadura +1",
  "armor-2": "Armadura +2",
  "armor-3": "Armadura +3",
  "armor-of-invulnerability": "Armadura de Invulnerabilidade",
  "armor-of-resistance": "Armadura de Resistência",
  "armor-of-vulnerability": "Armadura de Vulnerabilidade",
  "arrow-catching-shield": "Escudo Apanhador de Flechas",
  "arrow-of-slaying": "Flecha Matadora",
  "bag-of-beans": "Bolsa de Feijões",
  "bag-of-devouring": "Bolsa Devoradora",
  "bag-of-holding": "Bolsa de Armazenamento",
  "bag-of-tricks": "Bolsa de Truques",
  "belt-of-dwarvenkind": "Cinto da Raça Anã",
  "belt-of-giant-strength": "Cinto de Força Gigante",
  "berserker-axe": "Machado do Berserker",
  "boots-of-elvenkind": "Botas Élficas",
  "boots-of-levitation": "Botas de Levitação",
  "boots-of-speed": "Botas de Velocidade",
  "boots-of-striding-and-springing": "Botas de Marcha e Salto",
  "boots-of-the-winterlands": "Botas das Terras Invernais",
  "bowl-of-commanding-water-elementals": "Tigela de Comandar Elementais da Água",
  "bracers-of-archery": "Braceletes de Arqueiro",
  "bracers-of-defense": "Braceletes de Defesa",
  "brazier-of-commanding-fire-elementals": "Braseiro de Comandar Elementais do Fogo",
  "brooch-of-shielding": "Broche de Proteção",
  "broom-of-flying": "Vassoura Voadora",
  "candle-of-invocation": "Vela de Invocação",
  "cape-of-the-mountebank": "Capa do Charlatão",
  "carpet-of-flying": "Tapete Voador",
  "censer-of-controlling-air-elementals": "Incensário de Controlar Elementais do Ar",
  "circlet-of-blasting": "Diadema de Destruição",
  "cloak-of-arachnida": "Manto de Aracnídeo",
  "cloak-of-displacement": "Manto de Deslocamento",
  "cloak-of-elvenkind": "Manto Élfico",
  "cloak-of-invisibility": "Manto de Invisibilidade",
  "cloak-of-protection": "Manto de Proteção",
  "cloak-of-the-bat": "Manto do Morcego",
  "cloak-of-the-manta-ray": "Manto da Raia Manta",
  "crystal-ball": "Bola de Cristal",
  "cube-of-force": "Cubo de Força",
  "cubic-gate": "Portal Cúbico",
  "dagger-of-venom": "Adaga de Veneno",
  "dancing-sword": "Espada Dançante",
  "decanter-of-endless-water": "Jarro de Água Infinita",
  "deck-of-illusions": "Baralho de Ilusões",
  "deck-of-many-things": "Baralho de Várias Coisas",
  "defender": "Defensora",
  "demon-armor": "Armadura Demoníaca",
  "dimensional-shackles": "Algemas Dimensionais",
  "dragon-scale-mail": "Cota de Escamas de Dragão",
  "dragon-slayer": "Matadora de Dragões",
  "dust-of-disappearance": "Pó do Desaparecimento",
  "dust-of-dryness": "Pó da Secura",
  "dust-of-sneezing-and-choking": "Pó de Espirro e Sufocamento",
  "dwarven-plate": "Armadura de Placas Anã",
  "dwarven-thrower": "Arremessadora Anã",
  "efficient-quiver": "Aljava Eficiente",
  "efreeti-bottle": "Garrafa do Efreeti",
  "efreeti-chain": "Corrente do Efreeti",
  "elemental-gem": "Gema Elemental",
  "elven-chain": "Cota Élfica",
  "eversmoking-bottle": "Garrafa de Fumaça Eterna",
  "eyes-of-charming": "Olhos de Fascínio",
  "eyes-of-minute-seeing": "Olhos de Visão Minuciosa",
  "eyes-of-the-eagle": "Olhos da Águia",
  "feather-token": "Ficha de Pena",
  "figurine-of-wondrous-power": "Estatueta de Poder Maravilhoso",
  "flame-tongue": "Língua de Fogo",
  "folding-boat": "Barco Dobrável",
  "frost-brand": "Marca de Gelo",
  "gauntlets-of-ogre-power": "Manoplas de Força de Ogro",
  "gem-of-brightness": "Gema de Brilho",
  "gem-of-seeing": "Gema de Visão",
  "giant-slayer": "Matadora de Gigantes",
  "glamoured-studded-leather": "Couro Cravejado Glamoroso",
  "gloves-of-missile-snaring": "Luvas Pega-Mísseis",
  "gloves-of-swimming-and-climbing": "Luvas de Natação e Escalada",
  "goggles-of-night": "Óculos da Noite",
  "hammer-of-thunderbolts": "Martelo dos Raios",
  "handy-haversack": "Mochila Prática",
  "hat-of-disguise": "Chapéu de Disfarce",
  "headband-of-intellect": "Faixa de Intelecto",
  "helm-of-brilliance": "Elmo de Brilho",
  "helm-of-comprehending-languages": "Elmo de Compreensão de Idiomas",
  "helm-of-telepathy": "Elmo de Telepatia",
  "helm-of-teleportation": "Elmo de Teletransporte",
  "holy-avenger": "Vingador Sagrado",
  "horn-of-blasting": "Trombeta de Destruição",
  "horn-of-valhalla": "Trombeta de Valhalla",
  "horseshoes-of-a-zephyr": "Ferraduras do Zéfiro",
  "horseshoes-of-speed": "Ferraduras de Velocidade",
  "immovable-rod": "Bastão Inamovível",
  "instant-fortress": "Fortaleza Instantânea",
  "instrument-of-the-bards": "Instrumento dos Bardos",
  "ioun-stone": "Pedra Ioun",
  "iron-bands-of-binding": "Faixas de Ferro de Aprisionamento",
  "iron-flask": "Frasco de Ferro",
  "javelin-of-lightning": "Azagaia de Relâmpago",
  "lantern-of-revealing": "Lanterna Reveladora",
  "luck-blade": "Lâmina da Sorte",
  "mace-of-disruption": "Maça da Disrupção",
  "mace-of-smiting": "Maça Destruidora",
  "mace-of-terror": "Maça do Terror",
  "mantle-of-spell-resistance": "Manto de Resistência a Magia",
  "manual-of-bodily-health": "Manual de Saúde Corporal",
  "manual-of-gainful-exercise": "Manual de Exercícios Proveitosos",
  "manual-of-golems": "Manual de Golens",
  "manual-of-quickness-of-action": "Manual de Agilidade em Ação",
  "marvelous-pigments": "Pigmentos Maravilhosos",
  "medallion-of-thoughts": "Medalhão de Pensamentos",
  "mirror-of-life-trapping": "Espelho de Aprisionamento Vital",
  "mithral-armor": "Armadura de Mithral",
  "necklace-of-adaptation": "Colar de Adaptação",
  "necklace-of-fireballs": "Colar de Bolas de Fogo",
  "necklace-of-prayer-beads": "Colar de Contas de Oração",
  "nine-lives-stealer": "Roubadora de Nove Vidas",
  "oathbow": "Arco do Juramento",
  "oil-of-etherealness": "Óleo de Eterealidade",
  "oil-of-sharpness": "Óleo de Afiação",
  "oil-of-slipperiness": "Óleo de Escorregamento",
  "pearl-of-power": "Pérola de Poder",
  "periapt-of-health": "Amuleto de Saúde",
  "periapt-of-proof-against-poison": "Amuleto contra Veneno",
  "periapt-of-wound-closure": "Amuleto de Cura de Feridas",
  "philter-of-love": "Filtro do Amor",
  "pipes-of-haunting": "Flautas Assombrosas",
  "pipes-of-the-sewers": "Flautas dos Esgotos",
  "plate-armor-of-etherealness": "Armadura de Placas de Eterealidade",
  "portable-hole": "Buraco Portátil",
  "potion-of-animal-friendship": "Poção de Amizade Animal",
  "potion-of-clairvoyance": "Poção de Clarividência",
  "potion-of-climbing": "Poção de Escalada",
  "potion-of-diminution": "Poção de Diminuição",
  "potion-of-fire-breath": "Poção de Sopro de Fogo",
  "potion-of-flying": "Poção de Voo",
  "potion-of-gaseous-form": "Poção de Forma Gasosa",
  "potion-of-giant-strength": "Poção de Força Gigante",
  "potion-of-growth": "Poção de Crescimento",
  "potion-of-healing": "Poção de Cura",
  "potion-of-heroism": "Poção de Heroísmo",
  "potion-of-invisibility": "Poção de Invisibilidade",
  "potion-of-mind-reading": "Poção de Leitura Mental",
  "potion-of-poison": "Poção de Veneno",
  "potion-of-resistance": "Poção de Resistência",
  "potion-of-speed": "Poção de Velocidade",
  "potion-of-water-breathing": "Poção de Respiração Aquática",
  "prayer-bead": "Conta de Oração",
  "quaals-feather-token": "Ficha de Pena de Quaal",
  "ring-of-animal-influence": "Anel de Influência Animal",
  "ring-of-djinni-summoning": "Anel de Invocar Djinn",
  "ring-of-elemental-command": "Anel de Comando Elemental",
  "ring-of-evasion": "Anel de Evasão",
  "ring-of-feather-falling": "Anel de Queda Suave",
  "ring-of-free-action": "Anel de Ação Livre",
  "ring-of-invisibility": "Anel de Invisibilidade",
  "ring-of-jumping": "Anel de Salto",
  "ring-of-mind-shielding": "Anel de Proteção Mental",
  "ring-of-protection": "Anel de Proteção",
  "ring-of-regeneration": "Anel de Regeneração",
  "ring-of-resistance": "Anel de Resistência",
  "ring-of-shooting-stars": "Anel de Estrelas Cadentes",
  "ring-of-spell-storing": "Anel de Armazenar Magias",
  "ring-of-spell-turning": "Anel de Rebater Magias",
  "ring-of-swimming": "Anel de Natação",
  "ring-of-telekinesis": "Anel de Telecinese",
  "ring-of-the-ram": "Anel do Carneiro",
  "ring-of-three-wishes": "Anel de Três Desejos",
  "ring-of-warmth": "Anel de Aquecimento",
  "ring-of-water-walking": "Anel de Caminhar na Água",
  "ring-of-x-ray-vision": "Anel de Visão de Raio-X",
  "robe-of-eyes": "Manto dos Olhos",
  "robe-of-scintillating-colors": "Manto de Cores Cintilantes",
  "robe-of-stars": "Manto das Estrelas",
  "robe-of-the-archmagi": "Manto do Arquimago",
  "robe-of-useful-items": "Manto de Itens Úteis",
  "rod-of-absorption": "Bastão de Absorção",
  "rod-of-alertness": "Bastão de Alerta",
  "rod-of-lordly-might": "Bastão de Poder Soberano",
  "rod-of-rulership": "Bastão de Comando",
  "rod-of-security": "Bastão de Segurança",
  "rope-of-climbing": "Corda de Escalada",
  "rope-of-entanglement": "Corda de Enredamento",
  "scarab-of-protection": "Escaravelho de Proteção",
  "scimitar-of-speed": "Cimitarra de Velocidade",
  "shield-1": "Escudo +1",
  "shield-2": "Escudo +2",
  "shield-3": "Escudo +3",
  "slippers-of-spider-climbing": "Sandálias de Escalada de Aranha",
  "sovereign-glue": "Cola Soberana",
  "spell-scroll": "Pergaminho de Magia",
  "spellguard-shield": "Escudo Guarda-Feitiço",
  "sphere-of-annihilation": "Esfera de Aniquilação",
  "staff-of-charming": "Cajado de Fascínio",
  "staff-of-fire": "Cajado de Fogo",
  "staff-of-frost": "Cajado de Gelo",
  "staff-of-healing": "Cajado de Cura",
  "staff-of-power": "Cajado de Poder",
  "staff-of-striking": "Cajado Percussor",
  "staff-of-swarming-insects": "Cajado de Enxame de Insetos",
  "staff-of-the-magi": "Cajado do Mago",
  "staff-of-the-python": "Cajado da Píton",
  "staff-of-the-woodlands": "Cajado dos Bosques",
  "staff-of-thunder-and-lightning": "Cajado de Trovão e Relâmpago",
  "staff-of-withering": "Cajado da Decomposição",
  "stone-of-controlling-earth-elementals": "Pedra de Controlar Elementais da Terra",
  "stone-of-good-luck-luckstone": "Pedra da Sorte",
  "sun-blade": "Lâmina Solar",
  "sword-of-answering": "Espada de Resposta",
  "sword-of-life-stealing": "Espada Roubadora de Vida",
  "sword-of-sharpness": "Espada Afiada",
  "sword-of-wounding": "Espada Feridora",
  "talisman-of-pure-good": "Talismã do Bem Puro",
  "talisman-of-the-sphere": "Talismã da Esfera",
  "talisman-of-ultimate-evil": "Talismã do Mal Supremo",
  "tome-of-clear-thought": "Tomo de Pensamento Claro",
  "tome-of-leadership-and-influence": "Tomo de Liderança e Influência",
  "tome-of-understanding": "Tomo de Compreensão",
  "trident-of-fish-command": "Tridente de Comando de Peixes",
  "universal-solvent": "Solvente Universal",
  "vicious-weapon": "Arma Cruel",
  "vorpal-sword": "Espada Vorpal",
  "wand-of-binding": "Varinha de Aprisionamento",
  "wand-of-enemy-detection": "Varinha de Detecção de Inimigos",
  "wand-of-fear": "Varinha do Medo",
  "wand-of-fireballs": "Varinha de Bolas de Fogo",
  "wand-of-lightning-bolts": "Varinha de Relâmpagos",
  "wand-of-magic-detection": "Varinha de Detecção de Magia",
  "wand-of-magic-missiles": "Varinha de Mísseis Mágicos",
  "wand-of-paralysis": "Varinha de Paralisia",
  "wand-of-polymorph": "Varinha de Polimorfar",
  "wand-of-secrets": "Varinha de Segredos",
  "wand-of-the-war-mage-1": "Varinha do Mago de Guerra +1",
  "wand-of-the-war-mage-2": "Varinha do Mago de Guerra +2",
  "wand-of-the-war-mage-3": "Varinha do Mago de Guerra +3",
  "wand-of-web": "Varinha de Teia",
  "wand-of-wonder": "Varinha de Maravilhas",
  "weapon-1": "Arma +1",
  "weapon-2": "Arma +2",
  "weapon-3": "Arma +3",
  "well-of-many-worlds": "Poço de Muitos Mundos",
  "wind-fan": "Leque de Vento",
  "winged-boots": "Botas Aladas",
  "wings-of-flying": "Asas de Voo",
  // Variantes faltantes
  "ammunition": "Munição",
  "armor": "Armadura",
  "bag-of-tricks-gray": "Bolsa de Truques (Cinza)",
  "bag-of-tricks-rust": "Bolsa de Truques (Ferrugem)",
  "bag-of-tricks-tan": "Bolsa de Truques (Bege)",
  "bead-of-force": "Esfera de Força",
  "belt-of-giant-strength-cloud": "Cinto de Força de Gigante das Nuvens",
  "belt-of-giant-strength-fire": "Cinto de Força de Gigante do Fogo",
  "belt-of-giant-strength-frost": "Cinto de Força de Gigante do Gelo",
  "belt-of-giant-strength-hill": "Cinto de Força de Gigante das Colinas",
  "belt-of-giant-strength-stone": "Cinto de Força de Gigante de Pedra",
  "belt-of-giant-strength-storm": "Cinto de Força de Gigante da Tempestade",
  "carpet-of-flying-3x5": "Tapete Voador (1×1,5 m)",
  "carpet-of-flying-4x6": "Tapete Voador (1,2×1,8 m)",
  "carpet-of-flying-5x7": "Tapete Voador (1,5×2,1 m)",
  "carpet-of-flying-6x9": "Tapete Voador (1,8×2,7 m)",
  "chime-of-opening": "Sino de Abertura",
  "crystal-ball-of-mind-reading": "Bola de Cristal de Leitura Mental",
  "crystal-ball-of-telepathy": "Bola de Cristal de Telepatia",
  "crystal-ball-of-true-seeing": "Bola de Cristal de Visão Verdadeira",
  "horn-of-valhalla-brass": "Trombeta de Valhalla (Latão)",
  "horn-of-valhalla-bronze": "Trombeta de Valhalla (Bronze)",
  "horn-of-valhalla-iron": "Trombeta de Valhalla (Ferro)",
  "horn-of-valhalla-silver": "Trombeta de Valhalla (Prata)",
  "instrument-of-the-bards-anstruth-harp": "Instrumento dos Bardos — Harpa Anstruth",
  "instrument-of-the-bards-canaith-mandolin": "Instrumento dos Bardos — Bandolim Canaith",
  "instrument-of-the-bards-cli-lyre": "Instrumento dos Bardos — Lira Cli",
  "instrument-of-the-bards-doss-lute": "Instrumento dos Bardos — Alaúde Doss",
  "instrument-of-the-bards-fochlucan-bandore": "Instrumento dos Bardos — Bandola Fochlucan",
  "instrument-of-the-bards-mac-fuirmidh-cittern": "Instrumento dos Bardos — Cítara Mac-Fuirmidh",
  "instrument-of-the-bards-ollamh-harp": "Instrumento dos Bardos — Harpa Ollamh",
  "ioun-stone-absorption": "Pedra Ioun (Absorção)",
  "ioun-stone-agility": "Pedra Ioun (Agilidade)",
  "ioun-stone-awareness": "Pedra Ioun (Consciência)",
  "ioun-stone-fortitude": "Pedra Ioun (Fortitude)",
  "ioun-stone-greater-absorption": "Pedra Ioun (Absorção Maior)",
  "ioun-stone-insight": "Pedra Ioun (Perspicácia)",
  "ioun-stone-intellect": "Pedra Ioun (Intelecto)",
  "ioun-stone-leadership": "Pedra Ioun (Liderança)",
  "ioun-stone-mastery": "Pedra Ioun (Maestria)",
  "ioun-stone-protection": "Pedra Ioun (Proteção)",
  "ioun-stone-regeneration": "Pedra Ioun (Regeneração)",
  "ioun-stone-reserve": "Pedra Ioun (Reserva)",
  "ioun-stone-strength": "Pedra Ioun (Força)",
  "ioun-stone-sustenance": "Pedra Ioun (Sustento)",
  "potion-of-fire-giant-strength": "Poção de Força de Gigante do Fogo",
  "potion-of-frost-giant-strength": "Poção de Força de Gigante do Gelo",
  "potion-of-hill-giant-strength": "Poção de Força de Gigante das Colinas",
  "potion-of-stone-giant-strength": "Poção de Força de Gigante de Pedra",
  "potion-of-storm-giant-strength": "Poção de Força de Gigante da Tempestade",
  "potion-of-cloud-giant-strength": "Poção de Força de Gigante das Nuvens",
  "potion-of-greater-healing": "Poção de Cura Maior",
  "potion-of-superior-healing": "Poção de Cura Superior",
  "potion-of-supreme-healing": "Poção de Cura Suprema",
  "ring-of-air-elemental-command": "Anel de Comando de Elemental do Ar",
  "ring-of-earth-elemental-command": "Anel de Comando de Elemental da Terra",
  "ring-of-fire-elemental-command": "Anel de Comando de Elemental do Fogo",
  "ring-of-water-elemental-command": "Anel de Comando de Elemental da Água",
  "spell-scroll-1st-level": "Pergaminho de Magia (1° nível)",
  "spell-scroll-2nd-level": "Pergaminho de Magia (2° nível)",
  "spell-scroll-3rd-level": "Pergaminho de Magia (3° nível)",
  "spell-scroll-4th-level": "Pergaminho de Magia (4° nível)",
  "spell-scroll-5th-level": "Pergaminho de Magia (5° nível)",
  "spell-scroll-6th-level": "Pergaminho de Magia (6° nível)",
  "spell-scroll-7th-level": "Pergaminho de Magia (7° nível)",
  "spell-scroll-8th-level": "Pergaminho de Magia (8° nível)",
  "spell-scroll-9th-level": "Pergaminho de Magia (9° nível)",
  "spell-scroll-cantrip": "Pergaminho de Magia (Truque)",
  "weapon": "Arma",
  // Variantes de Dragon Scale Mail
  "dragon-scale-mail-black": "Cota de Escamas de Dragão Negro",
  "dragon-scale-mail-blue": "Cota de Escamas de Dragão Azul",
  "dragon-scale-mail-brass": "Cota de Escamas de Dragão de Latão",
  "dragon-scale-mail-bronze": "Cota de Escamas de Dragão de Bronze",
  "dragon-scale-mail-copper": "Cota de Escamas de Dragão de Cobre",
  "dragon-scale-mail-gold": "Cota de Escamas de Dragão Dourado",
  "dragon-scale-mail-green": "Cota de Escamas de Dragão Verde",
  "dragon-scale-mail-red": "Cota de Escamas de Dragão Vermelho",
  "dragon-scale-mail-silver": "Cota de Escamas de Dragão Prateado",
  "dragon-scale-mail-white": "Cota de Escamas de Dragão Branco",
  // Gemas Elementais
  "elemental-gem-air": "Gema Elemental (Ar)",
  "elemental-gem-earth": "Gema Elemental (Terra)",
  "elemental-gem-fire": "Gema Elemental (Fogo)",
  "elemental-gem-water": "Gema Elemental (Água)",
  // Fichas de Pena
  "feather-token-anchor": "Ficha de Pena (Âncora)",
  "feather-token-bird": "Ficha de Pena (Pássaro)",
  "feather-token-fan": "Ficha de Pena (Leque)",
  "feather-token-swan-boat": "Ficha de Pena (Barco-Cisne)",
  "feather-token-tree": "Ficha de Pena (Árvore)",
  "feather-token-whip": "Ficha de Pena (Chicote)",
  // Figurines
  "figurine-of-wondrous-power-bronze-griffon": "Estatueta de Poder Maravilhoso (Grifo de Bronze)",
  "figurine-of-wondrous-power-ebony-fly": "Estatueta de Poder Maravilhoso (Mosca de Ébano)",
  "figurine-of-wondrous-power-golden-lions": "Estatueta de Poder Maravilhoso (Leões Dourados)",
  "figurine-of-wondrous-power-ivory-goats": "Estatueta de Poder Maravilhoso (Bodes de Marfim)",
  "figurine-of-wondrous-power-marble-elephant": "Estatueta de Poder Maravilhoso (Elefante de Mármore)",
  "figurine-of-wondrous-power-obsidian-steed": "Estatueta de Poder Maravilhoso (Corcel de Obsidiana)",
  "figurine-of-wondrous-power-onyx-dog": "Estatueta de Poder Maravilhoso (Cão de Ônix)",
  "figurine-of-wondrous-power-serpentine-owl": "Estatueta de Poder Maravilhoso (Coruja de Serpentina)",
  "figurine-of-wondrous-power-silver-raven": "Estatueta de Poder Maravilhoso (Corvo de Prata)",
  // Manuais de Golem
  "manual-of-clay-golems": "Manual de Golens de Argila",
  "manual-of-flesh-golems": "Manual de Golens de Carne",
  "manual-of-iron-golems": "Manual de Golens de Ferro",
  "manual-of-stone-golems": "Manual de Golens de Pedra",
  // Resistência por tipo de dano
  "armor-of-acid-resistance": "Armadura de Resistência a Ácido",
  "armor-of-cold-resistance": "Armadura de Resistência a Frio",
  "armor-of-fire-resistance": "Armadura de Resistência a Fogo",
  "armor-of-force-resistance": "Armadura de Resistência a Força",
  "armor-of-lightning-resistance": "Armadura de Resistência a Relâmpago",
  "armor-of-necrotic-resistance": "Armadura de Resistência a Necrótico",
  "armor-of-poison-resistance": "Armadura de Resistência a Veneno",
  "armor-of-psychic-resistance": "Armadura de Resistência a Psíquico",
  "armor-of-radiant-resistance": "Armadura de Resistência a Radiante",
  "armor-of-thunder-resistance": "Armadura de Resistência a Trovão",
  "ring-of-acid-resistance": "Anel de Resistência a Ácido",
  "ring-of-cold-resistance": "Anel de Resistência a Frio",
  "ring-of-fire-resistance": "Anel de Resistência a Fogo",
  "ring-of-force-resistance": "Anel de Resistência a Força",
  "ring-of-lightning-resistance": "Anel de Resistência a Relâmpago",
  "ring-of-necrotic-resistance": "Anel de Resistência a Necrótico",
  "ring-of-poison-resistance": "Anel de Resistência a Veneno",
  "ring-of-psychic-resistance": "Anel de Resistência a Psíquico",
  "ring-of-radiant-resistance": "Anel de Resistência a Radiante",
  "ring-of-thunder-resistance": "Anel de Resistência a Trovão",
  "potion-of-acid-resistance": "Poção de Resistência a Ácido",
  "potion-of-cold-resistance": "Poção de Resistência a Frio",
  "potion-of-fire-resistance": "Poção de Resistência a Fogo",
  "potion-of-force-resistance": "Poção de Resistência a Força",
  "potion-of-lightning-resistance": "Poção de Resistência a Relâmpago",
  "potion-of-necrotic-resistance": "Poção de Resistência a Necrótico",
  "potion-of-poison-resistance": "Poção de Resistência a Veneno",
  "potion-of-psychic-resistance": "Poção de Resistência a Psíquico",
  "potion-of-radiant-resistance": "Poção de Resistência a Radiante",
  "potion-of-thunder-resistance": "Poção de Resistência a Trovão",
  // Sword of Answering variants
  "sword-of-answering-answerer": "Espada de Resposta (Respondedora)",
  "sword-of-answering-back-talker": "Espada de Resposta (Retrucadora)",
  "sword-of-answering-concluder": "Espada de Resposta (Conclusora)",
  "sword-of-answering-last-quip": "Espada de Resposta (Última Piada)",
  "sword-of-answering-rebutter": "Espada de Resposta (Rebatedora)",
  "sword-of-answering-replier": "Espada de Resposta (Replicadora)",
  "sword-of-answering-retorter": "Espada de Resposta (Retorquira)",
  "sword-of-answering-scather": "Espada de Resposta (Flageladora)",
  "sword-of-answering-squelcher": "Espada de Resposta (Silenciadora)",
  // Variantes de índice alternativo (ioun-stone-of-X ao invés de ioun-stone-X)
  "glamoured-studded-leather-armor": "Couro Cravejado Glamoroso",
  "ioun-stone-of-absorption": "Pedra Ioun (Absorção)",
  "ioun-stone-of-agility": "Pedra Ioun (Agilidade)",
  "ioun-stone-of-awareness": "Pedra Ioun (Consciência)",
  "ioun-stone-of-fortitude": "Pedra Ioun (Fortitude)",
  "ioun-stone-of-greater-absorption": "Pedra Ioun (Absorção Maior)",
  "ioun-stone-of-insight": "Pedra Ioun (Perspicácia)",
  "ioun-stone-of-intellect": "Pedra Ioun (Intelecto)",
  "ioun-stone-of-leadership": "Pedra Ioun (Liderança)",
  "ioun-stone-of-mastery": "Pedra Ioun (Maestria)",
  "ioun-stone-of-protection": "Pedra Ioun (Proteção)",
  "ioun-stone-of-regeneration": "Pedra Ioun (Regeneração)",
  "ioun-stone-of-reserve": "Pedra Ioun (Reserva)",
  "ioun-stone-of-strength": "Pedra Ioun (Força)",
  "ioun-stone-of-sustenance": "Pedra Ioun (Sustento)",
  "manual-of-golems-clay": "Manual de Golens de Argila",
  "manual-of-golems-flesh": "Manual de Golens de Carne",
  "manual-of-golems-iron": "Manual de Golens de Ferro",
  "manual-of-golems-stone": "Manual de Golens de Pedra",
  "orb-of-dragonkind": "Orbe do Sangue Dracônico",
  "potion-of-healing-greater": "Poção de Cura Maior",
  "potion-of-healing-superior": "Poção de Cura Superior",
  "potion-of-healing-supreme": "Poção de Cura Suprema",
  "robe-of-the-archmagi-evil": "Manto do Arquimago (Mal)",
  "robe-of-the-archmagi-good": "Manto do Arquimago (Bem)",
  "robe-of-the-archmagi-neutral": "Manto do Arquimago (Neutro)",
  "shield": "Escudo",
  // Últimas variantes faltantes
  "potion-of-giant-strength-cloud": "Poção de Força de Gigante das Nuvens",
  "potion-of-giant-strength-fire": "Poção de Força de Gigante do Fogo",
  "potion-of-giant-strength-frost": "Poção de Força de Gigante do Gelo",
  "potion-of-giant-strength-hill": "Poção de Força de Gigante das Colinas",
  "potion-of-giant-strength-stone": "Poção de Força de Gigante de Pedra",
  "potion-of-giant-strength-storm": "Poção de Força de Gigante da Tempestade",
  "potion-of-healing-common": "Poção de Cura (Comum)",
  "potion-of-resistance-acid": "Poção de Resistência a Ácido",
  "potion-of-resistance-cold": "Poção de Resistência a Frio",
  "potion-of-resistance-fire": "Poção de Resistência a Fogo",
  "potion-of-resistance-force": "Poção de Resistência a Força",
  "potion-of-resistance-lightning": "Poção de Resistência a Relâmpago",
  "potion-of-resistance-necrotic": "Poção de Resistência a Necrótico",
  "potion-of-resistance-poison": "Poção de Resistência a Veneno",
  "potion-of-resistance-psychic": "Poção de Resistência a Psíquico",
  "potion-of-resistance-radiant": "Poção de Resistência a Radiante",
  "potion-of-resistance-thunder": "Poção de Resistência a Trovão",
  "restorative-ointment": "Unguento Restaurador",
  "ring-of-elemental-command-air": "Anel de Comando Elemental (Ar)",
  "ring-of-elemental-command-earth": "Anel de Comando Elemental (Terra)",
  "ring-of-elemental-command-fire": "Anel de Comando Elemental (Fogo)",
  "ring-of-elemental-command-water": "Anel de Comando Elemental (Água)",
  "ring-of-resistance-acid": "Anel de Resistência a Ácido",
  "ring-of-resistance-cold": "Anel de Resistência a Frio",
  "ring-of-resistance-fire": "Anel de Resistência a Fogo",
  "ring-of-resistance-force": "Anel de Resistência a Força",
  "ring-of-resistance-lightning": "Anel de Resistência a Relâmpago",
  "ring-of-resistance-necrotic": "Anel de Resistência a Necrótico",
  "ring-of-resistance-poison": "Anel de Resistência a Veneno",
  "ring-of-resistance-psychic": "Anel de Resistência a Psíquico",
  "ring-of-resistance-radiant": "Anel de Resistência a Radiante",
  "ring-of-resistance-thunder": "Anel de Resistência a Trovão",
  "rod-of-the-pact-keeper-1": "Bastão do Guardião do Pacto +1",
  "rod-of-the-pact-keeper-2": "Bastão do Guardião do Pacto +2",
  "rod-of-the-pact-keeper-3": "Bastão do Guardião do Pacto +3",
  "sentinel-shield": "Escudo Sentinela",
  "shield-of-missile-attraction": "Escudo de Atração de Mísseis",
  "spell-scroll-1": "Pergaminho de Magia (1° nível)",
  "spell-scroll-2": "Pergaminho de Magia (2° nível)",
  "spell-scroll-3": "Pergaminho de Magia (3° nível)",
  "spell-scroll-4": "Pergaminho de Magia (4° nível)",
  "spell-scroll-5": "Pergaminho de Magia (5° nível)",
  "spell-scroll-6": "Pergaminho de Magia (6° nível)",
  "spell-scroll-7": "Pergaminho de Magia (7° nível)",
  "spell-scroll-8": "Pergaminho de Magia (8° nível)",
  "spell-scroll-9": "Pergaminho de Magia (9° nível)",
  "tome-of-the-stilled-tongue": "Tomo da Língua Silenciada",
  "wand-of-the-war-mage": "Varinha do Mago de Guerra",
  "spell-scroll-1st": "Pergaminho de Magia (1° nível)",
  "spell-scroll-2nd": "Pergaminho de Magia (2° nível)",
  "spell-scroll-3rd": "Pergaminho de Magia (3° nível)",
  "spell-scroll-4th": "Pergaminho de Magia (4° nível)",
  "spell-scroll-5th": "Pergaminho de Magia (5° nível)",
  "spell-scroll-6th": "Pergaminho de Magia (6° nível)",
  "spell-scroll-7th": "Pergaminho de Magia (7° nível)",
  "spell-scroll-8th": "Pergaminho de Magia (8° nível)",
  "spell-scroll-9th": "Pergaminho de Magia (9° nível)",
};

// Feat
export const featNames: Record<string, string> = {
  "grappler": "Agarrador",
};
