// Nomes oficiais PT-BR dos monstros do SRD 5e
// Fonte: Manual dos Monstros D&D 5e em Português (Galápagos Jogos / WotC)
export const monsterNames: Record<string, string> = {
  "aboleth": "Abolete",
  "acolyte": "Acólito",
  "adult-black-dragon": "Dragão Negro Adulto",
  "adult-blue-dragon": "Dragão Azul Adulto",
  "adult-brass-dragon": "Dragão de Latão Adulto",
  "adult-bronze-dragon": "Dragão de Bronze Adulto",
  "adult-copper-dragon": "Dragão de Cobre Adulto",
  "adult-gold-dragon": "Dragão Dourado Adulto",
  "adult-green-dragon": "Dragão Verde Adulto",
  "adult-red-dragon": "Dragão Vermelho Adulto",
  "adult-silver-dragon": "Dragão Prateado Adulto",
  "adult-white-dragon": "Dragão Branco Adulto",
  "air-elemental": "Elemental do Ar",
  "ancient-black-dragon": "Dragão Negro Ancião",
  "ancient-blue-dragon": "Dragão Azul Ancião",
  "ancient-brass-dragon": "Dragão de Latão Ancião",
  "ancient-bronze-dragon": "Dragão de Bronze Ancião",
  "ancient-copper-dragon": "Dragão de Cobre Ancião",
  "ancient-gold-dragon": "Dragão Dourado Ancião",
  "ancient-green-dragon": "Dragão Verde Ancião",
  "ancient-red-dragon": "Dragão Vermelho Ancião",
  "ancient-silver-dragon": "Dragão Prateado Ancião",
  "ancient-white-dragon": "Dragão Branco Ancião",
  "androsphinx": "Androesfinge",
  "animated-armor": "Armadura Animada",
  "ankheg": "Ankheg",
  "ape": "Macaco",
  "archmage": "Arquimago",
  "assassin": "Assassino",
  "awakened-shrub": "Arbusto Desperto",
  "awakened-tree": "Árvore Desperta",
  "axe-beak": "Bico-de-Machado",
  "azer": "Azer",
  "baboon": "Babuíno",
  "badger": "Texugo",
  "balor": "Balor",
  "bandit": "Bandido",
  "bandit-captain": "Capitão Bandido",
  "barbed-devil": "Diabo Espinhoso",
  "basilisk": "Basilisco",
  "bat": "Morcego",
  "bear-black": "Urso Negro",
  "bear-brown": "Urso Pardo",
  "bear-polar": "Urso Polar",
  "bearded-devil": "Diabo Barbado",
  "behir": "Behir",
  "berserker": "Berserker",
  "black-bear": "Urso Negro",
  "black-dragon-wyrmling": "Filhote de Dragão Negro",
  "black-pudding": "Pudim Negro",
  "blink-dog": "Cão Teleportador",
  "blood-hawk": "Falcão Sanguinário",
  "blue-dragon-wyrmling": "Filhote de Dragão Azul",
  "boar": "Javali",
  "bone-devil": "Diabo Ósseo",
  "brass-dragon-wyrmling": "Filhote de Dragão de Latão",
  "bronze-dragon-wyrmling": "Filhote de Dragão de Bronze",
  "brown-bear": "Urso Pardo",
  "bugbear": "Bugbear",
  "bulette": "Bulette",
  "camel": "Camelo",
  "cat": "Gato",
  "centaur": "Centauro",
  "chain-devil": "Diabo de Correntes",
  "chimera": "Quimera",
  "chuul": "Chuul",
  "clay-golem": "Golem de Argila",
  "cloaker": "Manto Sombrio",
  "cloud-giant": "Gigante das Nuvens",
  "cockatrice": "Cocatriz",
  "commoner": "Plebeu",
  "constrictor-snake": "Cobra Constritora",
  "copper-dragon-wyrmling": "Filhote de Dragão de Cobre",
  "couatl": "Couatl",
  "crab": "Caranguejo",
  "crocodile": "Crocodilo",
  "cult-fanatic": "Fanático de Culto",
  "cultist": "Cultista",
  "darkmantle": "Manto Sombrio",
  "death-dog": "Cão da Morte",
  "deep-gnome-svirfneblin": "Gnomo das Profundezas",
  "deer": "Cervo",
  "deva": "Deva",
  "dire-wolf": "Lobo Gigante",
  "djinni": "Djinn",
  "doppelganger": "Doppelganger",
  "draft-horse": "Cavalo de Tração",
  "dragon-turtle": "Tartaruga-Dragão",
  "dretch": "Dretch",
  "drider": "Drider",
  "drow": "Drow",
  "druid": "Druida",
  "dryad": "Dríade",
  "duergar": "Duergar",
  "dust-mephit": "Mefita de Poeira",
  "eagle": "Águia",
  "earth-elemental": "Elemental da Terra",
  "efreeti": "Efreeti",
  "elephant": "Elefante",
  "elk": "Alce",
  "erinyes": "Erínias",
  "ettercap": "Ettercap",
  "ettin": "Ettin",
  "fire-elemental": "Elemental do Fogo",
  "fire-giant": "Gigante do Fogo",
  "flesh-golem": "Golem de Carne",
  "flying-snake": "Cobra Voadora",
  "flying-sword": "Espada Voadora",
  "frog": "Sapo",
  "frost-giant": "Gigante do Gelo",
  "gargoyle": "Gárgula",
  "gelatinous-cube": "Cubo Gelatinoso",
  "ghost": "Fantasma",
  "ghast": "Ghast",
  "ghoul": "Carniçal",
  "giant-ape": "Macaco Gigante",
  "giant-badger": "Texugo Gigante",
  "giant-bat": "Morcego Gigante",
  "giant-boar": "Javali Gigante",
  "giant-centipede": "Centopeia Gigante",
  "giant-constrictor-snake": "Cobra Constritora Gigante",
  "giant-crab": "Caranguejo Gigante",
  "giant-crocodile": "Crocodilo Gigante",
  "giant-eagle": "Águia Gigante",
  "giant-elk": "Alce Gigante",
  "giant-fire-beetle": "Besouro de Fogo Gigante",
  "giant-frog": "Sapo Gigante",
  "giant-goat": "Bode Gigante",
  "giant-hyena": "Hiena Gigante",
  "giant-lizard": "Lagarto Gigante",
  "giant-octopus": "Polvo Gigante",
  "giant-owl": "Coruja Gigante",
  "giant-poisonous-snake": "Cobra Venenosa Gigante",
  "giant-rat": "Rato Gigante",
  "giant-scorpion": "Escorpião Gigante",
  "giant-sea-horse": "Cavalo-Marinho Gigante",
  "giant-shark": "Tubarão Gigante",
  "giant-spider": "Aranha Gigante",
  "giant-toad": "Sapo Gigante",
  "giant-vulture": "Abutre Gigante",
  "giant-wasp": "Vespa Gigante",
  "giant-weasel": "Doninha Gigante",
  "giant-wolf-spider": "Aranha-Lobo Gigante",
  "gibbering-mouther": "Boca Murmurante",
  "glabrezu": "Glabrezu",
  "gladiator": "Gladiador",
  "gnoll": "Gnoll",
  "goat": "Bode",
  "goblin": "Goblin",
  "gold-dragon-wyrmling": "Filhote de Dragão Dourado",
  "gorgon": "Górgon",
  "gray-ooze": "Gosma Cinzenta",
  "green-dragon-wyrmling": "Filhote de Dragão Verde",
  "green-hag": "Bruxa Verde",
  "grick": "Grick",
  "griffon": "Grifo",
  "grimlock": "Grimlock",
  "guard": "Guarda",
  "guardian-naga": "Naga Guardiã",
  "gynosphinx": "Ginoesfinge",
  "half-red-dragon-veteran": "Veterano Meio-Dragão Vermelho",
  "harpy": "Harpia",
  "hawk": "Falcão",
  "hell-hound": "Cão Infernal",
  "hezrou": "Hezrou",
  "hill-giant": "Gigante das Colinas",
  "hippogriff": "Hipogrifo",
  "hobgoblin": "Hobgoblin",
  "homunculus": "Homúnculo",
  "horned-devil": "Diabo Cornudo",
  "hunter-shark": "Tubarão Caçador",
  "hydra": "Hidra",
  "hyena": "Hiena",
  "ice-devil": "Diabo do Gelo",
  "ice-mephit": "Mefita de Gelo",
  "imp": "Diabrete",
  "invisible-stalker": "Perseguidor Invisível",
  "iron-golem": "Golem de Ferro",
  "jackal": "Chacal",
  "jackalwere": "Licantropo-Chacal",
  "killer-whale": "Orca",
  "knight": "Cavaleiro",
  "kobold": "Kobold",
  "kraken": "Kraken",
  "lamia": "Lâmia",
  "lemure": "Lêmure",
  "lich": "Lich",
  "lion": "Leão",
  "lizard": "Lagarto",
  "lizardfolk": "Homem-Lagarto",
  "mage": "Mago",
  "magma-mephit": "Mefita de Magma",
  "magmin": "Magmin",
  "mammoth": "Mamute",
  "manticore": "Manticora",
  "marilith": "Marilith",
  "mastiff": "Mastim",
  "medusa": "Medusa",
  "merfolk": "Sereianos",
  "merrow": "Merrow",
  "mimic": "Mímico",
  "minotaur": "Minotauro",
  "minotaur-skeleton": "Esqueleto de Minotauro",
  "mule": "Mula",
  "mummy": "Múmia",
  "mummy-lord": "Múmia Lorde",
  "nalfeshnee": "Nalfeshnee",
  "night-hag": "Bruxa Noturna",
  "nightmare": "Pesadelo",
  "noble": "Nobre",
  "nothic": "Nothic",
  "ochre-jelly": "Geleia Ocre",
  "octopus": "Polvo",
  "ogre": "Ogro",
  "ogre-zombie": "Ogro Zumbi",
  "oni": "Oni",
  "orc": "Orc",
  "orc-war-chief": "Chefe de Guerra Orc",
  "otyugh": "Otyugh",
  "owl": "Coruja",
  "owlbear": "Urso-Coruja",
  "panther": "Pantera",
  "pegasus": "Pégaso",
  "phase-spider": "Aranha Fantasma",
  "pit-fiend": "Arquidiabo",
  "planetar": "Planetar",
  "plesiosaurus": "Plesiossauro",
  "poisonous-snake": "Cobra Venenosa",
  "polar-bear": "Urso Polar",
  "pony": "Pônei",
  "priest": "Sacerdote",
  "pseudodragon": "Pseudodragão",
  "pteranodon": "Pteranodonte",
  "purple-worm": "Verme Púrpura",
  "quasit": "Quasit",
  "quipper": "Piranha",
  "rakshasa": "Rakshasa",
  "rat": "Rato",
  "raven": "Corvo",
  "red-dragon-wyrmling": "Filhote de Dragão Vermelho",
  "reef-shark": "Tubarão de Recife",
  "remorhaz": "Remorhaz",
  "rhinoceros": "Rinoceronte",
  "riding-horse": "Cavalo de Montaria",
  "roc": "Roc",
  "roper": "Roper",
  "rug-of-smothering": "Tapete Sufocante",
  "rust-monster": "Monstro Ferrugem",
  "saber-toothed-tiger": "Tigre Dentes-de-Sabre",
  "sahuagin": "Sahuagin",
  "salamander": "Salamandra",
  "satyr": "Sátiro",
  "scorpion": "Escorpião",
  "scout": "Batedor",
  "sea-hag": "Bruxa do Mar",
  "sea-horse": "Cavalo-Marinho",
  "shadow": "Sombra",
  "shambling-mound": "Monte Cambaleante",
  "shield-guardian": "Guardião de Escudo",
  "shrieker": "Gritador",
  "silver-dragon-wyrmling": "Filhote de Dragão Prateado",
  "skeleton": "Esqueleto",
  "solar": "Solar",
  "specter": "Espectro",
  "spider": "Aranha",
  "spirit-naga": "Naga Espiritual",
  "sprite": "Sprite",
  "spy": "Espião",
  "steam-mephit": "Mefita de Vapor",
  "stirge": "Estirge",
  "stone-giant": "Gigante de Pedra",
  "stone-golem": "Golem de Pedra",
  "storm-giant": "Gigante da Tempestade",
  "succubus-incubus": "Súcubo/Íncubo",
  "swarm-of-bats": "Enxame de Morcegos",
  "swarm-of-insects": "Enxame de Insetos",
  "swarm-of-poisonous-snakes": "Enxame de Cobras Venenosas",
  "swarm-of-rats": "Enxame de Ratos",
  "swarm-of-ravens": "Enxame de Corvos",
  "tarrasque": "Tarrasque",
  "thug": "Capanga",
  "tiger": "Tigre",
  "treant": "Ent",
  "tribal-warrior": "Guerreiro Tribal",
  "triceratops": "Triceratops",
  "troll": "Troll",
  "turtle": "Tartaruga",
  "tyrannosaurus-rex": "Tiranossauro Rex",
  "unicorn": "Unicórnio",
  "vampire": "Vampiro",
  "vampire-spawn": "Cria Vampírica",
  "veteran": "Veterano",
  "violet-fungus": "Fungo Violeta",
  "vrock": "Vrock",
  "vulture": "Abutre",
  "warhorse": "Cavalo de Guerra",
  "warhorse-skeleton": "Esqueleto de Cavalo de Guerra",
  "water-elemental": "Elemental da Água",
  "weasel": "Doninha",
  "wereboar": "Javali-Licantropo",
  "wererat": "Rato-Licantropo",
  "weretiger": "Tigre-Licantropo",
  "werewolf": "Lobisomem",
  "white-dragon-wyrmling": "Filhote de Dragão Branco",
  "wight": "Wight",
  "will-o-wisp": "Fogo-Fátuo",
  "winter-wolf": "Lobo Invernal",
  "wolf": "Lobo",
  "worg": "Worg",
  "wraith": "Aparição",
  "wyvern": "Wyvern",
  "xorn": "Xorn",
  "young-black-dragon": "Dragão Negro Jovem",
  "young-blue-dragon": "Dragão Azul Jovem",
  "young-brass-dragon": "Dragão de Latão Jovem",
  "young-bronze-dragon": "Dragão de Bronze Jovem",
  "young-copper-dragon": "Dragão de Cobre Jovem",
  "young-gold-dragon": "Dragão Dourado Jovem",
  "young-green-dragon": "Dragão Verde Jovem",
  "young-red-dragon": "Dragão Vermelho Jovem",
  "young-silver-dragon": "Dragão Prateado Jovem",
  "young-white-dragon": "Dragão Branco Jovem",
  "zombie": "Zumbi",
  // Variantes faltantes
  "giant-rat-diseased": "Rato Gigante Doente",
  "swarm-of-beetles": "Enxame de Besouros",
  "swarm-of-centipedes": "Enxame de Centopeias",
  "swarm-of-quippers": "Enxame de Piranhas",
  "swarm-of-spiders": "Enxame de Aranhas",
  "swarm-of-wasps": "Enxame de Vespas",
  "vampire-bat": "Vampiro (Forma de Morcego)",
  "vampire-mist": "Vampiro (Forma de Névoa)",
  "vampire-vampire": "Vampiro",
  "werebear-bear": "Urso-Licantropo (Forma de Urso)",
  "werebear-human": "Urso-Licantropo (Forma Humana)",
  "werebear-hybrid": "Urso-Licantropo (Forma Híbrida)",
  "wereboar-boar": "Javali-Licantropo (Forma de Javali)",
  "wereboar-human": "Javali-Licantropo (Forma Humana)",
  "wereboar-hybrid": "Javali-Licantropo (Forma Híbrida)",
  "wererat-human": "Rato-Licantropo (Forma Humana)",
  "wererat-hybrid": "Rato-Licantropo (Forma Híbrida)",
  "wererat-rat": "Rato-Licantropo (Forma de Rato)",
  "weretiger-human": "Tigre-Licantropo (Forma Humana)",
  "weretiger-hybrid": "Tigre-Licantropo (Forma Híbrida)",
  "weretiger-tiger": "Tigre-Licantropo (Forma de Tigre)",
  "werewolf-human": "Lobisomem (Forma Humana)",
  "werewolf-hybrid": "Lobisomem (Forma Híbrida)",
  "werewolf-wolf": "Lobisomem (Forma de Lobo)",
};
