// Nomes oficiais PT-BR das magias do SRD 5e
// Fonte: Livro do Jogador D&D 5e em Português (Galápagos Jogos / WotC)
export const spellNames: Record<string, string> = {
  "acid-arrow": "Flecha Ácida",
  "acid-splash": "Borrifo Ácido",
  "aid": "Ajuda",
  "alarm": "Alarme",
  "alter-self": "Alterar-se",
  "animal-friendship": "Amizade Animal",
  "animal-messenger": "Mensageiro Animal",
  "animal-shapes": "Formas Animais",
  "animate-dead": "Animar Mortos",
  "animate-objects": "Animar Objetos",
  "antilife-shell": "Escudo Antivida",
  "antimagic-field": "Campo Antimagia",
  "antipathy-sympathy": "Antipatia/Simpatia",
  "arcane-eye": "Olho Arcano",
  "arcane-gate": "Portal Arcano",
  "arcane-hand": "Mão Arcana",
  "arcane-lock": "Tranca Arcana",
  "arcane-sword": "Espada Arcana",
  "arcanist-magic-aura": "Aura Mágica Arcana",
  "arcanists-magic-aura": "Aura Mágica Arcana",
  "astral-projection": "Projeção Astral",
  "augury": "Augúrio",
  "awaken": "Despertar",
  "bane": "Perdição",
  "banishment": "Banimento",
  "barkskin": "Pele de Árvore",
  "beacon-of-hope": "Farol de Esperança",
  "bestow-curse": "Rogar Maldição",
  "black-tentacles": "Tentáculos Negros",
  "blade-barrier": "Barreira de Lâminas",
  "bless": "Bênção",
  "blight": "Praga",
  "blindness-deafness": "Cegueira/Surdez",
  "blink": "Piscar",
  "blur": "Borrar",
  "branding-smite": "Golpe Marcante",
  "burning-hands": "Mãos Flamejantes",
  "call-lightning": "Invocar Relâmpago",
  "calm-emotions": "Acalmar Emoções",
  "chain-lightning": "Relâmpago em Cadeia",
  "charm-person": "Enfeitiçar Pessoa",
  "chill-touch": "Toque Gélido",
  "circle-of-death": "Círculo da Morte",
  "clairvoyance": "Clarividência",
  "clone": "Clone",
  "cloudkill": "Névoa Mortal",
  "color-spray": "Borrifo de Cores",
  "command": "Comando",
  "commune": "Comunhão",
  "commune-with-nature": "Comunhão com a Natureza",
  "comprehend-languages": "Compreender Idiomas",
  "compulsion": "Compulsão",
  "cone-of-cold": "Cone de Frio",
  "confusion": "Confusão",
  "conjure-animals": "Conjurar Animais",
  "conjure-celestial": "Conjurar Celestial",
  "conjure-elemental": "Conjurar Elemental",
  "conjure-fey": "Conjurar Fada",
  "conjure-minor-elementals": "Conjurar Elementais Menores",
  "conjure-woodland-beings": "Conjurar Seres Silvanos",
  "contact-other-plane": "Contatar Outro Plano",
  "contagion": "Contágio",
  "contingency": "Contingência",
  "continual-flame": "Chama Contínua",
  "control-water": "Controlar Água",
  "control-weather": "Controlar Clima",
  "counterspell": "Contramágica",
  "create-food-and-water": "Criar Comida e Água",
  "create-or-destroy-water": "Criar ou Destruir Água",
  "create-undead": "Criar Mortos-Vivos",
  "creation": "Criação",
  "cure-wounds": "Curar Ferimentos",
  "dancing-lights": "Luzes Dançantes",
  "darkness": "Escuridão",
  "darkvision": "Visão no Escuro",
  "daylight": "Luz do Dia",
  "death-ward": "Proteção contra a Morte",
  "delayed-blast-fireball": "Bola de Fogo Retardada",
  "demiplane": "Semiplano",
  "detect-evil-and-good": "Detectar o Bem e o Mal",
  "detect-magic": "Detectar Magia",
  "detect-poison-and-disease": "Detectar Veneno e Doença",
  "detect-thoughts": "Detectar Pensamentos",
  "dimension-door": "Porta Dimensional",
  "disguise-self": "Disfarçar-se",
  "disintegrate": "Desintegrar",
  "dispel-evil-and-good": "Dissipar o Bem e o Mal",
  "dispel-magic": "Dissipar Magia",
  "divination": "Adivinhação",
  "divine-favor": "Favor Divino",
  "divine-word": "Palavra Divina",
  "dominate-beast": "Dominar Besta",
  "dominate-monster": "Dominar Monstro",
  "dominate-person": "Dominar Pessoa",
  "dream": "Sonho",
  "druidcraft": "Druidismo",
  "earthquake": "Terremoto",
  "eldritch-blast": "Explosão Eldritch",
  "enhance-ability": "Aprimorar Habilidade",
  "enlarge-reduce": "Aumentar/Reduzir",
  "entangle": "Enredar",
  "enthrall": "Fascinar",
  "etherealness": "Forma Etérea",
  "expeditious-retreat": "Recuo Apressado",
  "eyebite": "Mau-Olhado",
  "fabricate": "Fabricar",
  "faerie-fire": "Fogo das Fadas",
  "faithful-hound": "Cão Fiel",
  "false-life": "Vida Falsa",
  "fear": "Medo",
  "feather-fall": "Queda Suave",
  "feeblemind": "Atrofiar Intelecto",
  "find-familiar": "Encontrar Familiar",
  "find-steed": "Encontrar Montaria",
  "find-the-path": "Encontrar o Caminho",
  "find-traps": "Encontrar Armadilhas",
  "finger-of-death": "Dedo da Morte",
  "fire-bolt": "Dardo de Fogo",
  "fire-shield": "Escudo de Fogo",
  "fire-storm": "Tempestade de Fogo",
  "fireball": "Bola de Fogo",
  "flame-blade": "Lâmina Flamejante",
  "flame-strike": "Coluna de Chamas",
  "flaming-sphere": "Esfera Flamejante",
  "flesh-to-stone": "Carne para Pedra",
  "floating-disk": "Disco Flutuante",
  "fly": "Voar",
  "fog-cloud": "Névoa",
  "forbiddance": "Interdição",
  "forcecage": "Jaula de Força",
  "foresight": "Previdência",
  "freedom-of-movement": "Liberdade de Movimento",
  "freezing-sphere": "Esfera Congelante",
  "gaseous-form": "Forma Gasosa",
  "gate": "Portal",
  "geas": "Missão",
  "gentle-repose": "Repouso Tranquilo",
  "giant-insect": "Inseto Gigante",
  "glibness": "Eloquência",
  "globe-of-invulnerability": "Globo de Invulnerabilidade",
  "glyph-of-warding": "Glifo de Proteção",
  "goodberry": "Fruto Bom",
  "grease": "Graxa",
  "greater-invisibility": "Invisibilidade Maior",
  "greater-restoration": "Restauração Maior",
  "guardian-of-faith": "Guardião da Fé",
  "guards-and-wards": "Guardas e Proteções",
  "guidance": "Orientação",
  "guiding-bolt": "Raio Guia",
  "gust-of-wind": "Rajada de Vento",
  "hallow": "Consagrar",
  "hallucinatory-terrain": "Terreno Ilusório",
  "harm": "Rigidez",
  "haste": "Velocidade",
  "heal": "Cura",
  "healing-word": "Palavra Curativa",
  "heat-metal": "Esquentar Metal",
  "hellish-rebuke": "Repreensão Infernal",
  "heroes-feast": "Banquete dos Heróis",
  "heroism": "Heroísmo",
  "hideous-laughter": "Riso Histérico",
  "hold-monster": "Imobilizar Monstro",
  "hold-person": "Imobilizar Pessoa",
  "holy-aura": "Aura Sagrada",
  "hunters-mark": "Marca do Caçador",
  "hypnotic-pattern": "Padrão Hipnótico",
  "ice-storm": "Tempestade de Gelo",
  "identify": "Identificação",
  "illusory-script": "Escrita Ilusória",
  "imprisonment": "Aprisionamento",
  "incendiary-cloud": "Nuvem Incendiária",
  "inflict-wounds": "Infligir Ferimentos",
  "insect-plague": "Praga de Insetos",
  "instant-summons": "Convocação Instantânea",
  "invisibility": "Invisibilidade",
  "irresistible-dance": "Dança Irresistível",
  "jump": "Salto",
  "knock": "Arrombar",
  "legend-lore": "Conhecimento de Lendas",
  "lesser-restoration": "Restauração Menor",
  "levitate": "Levitar",
  "light": "Luz",
  "lightning-bolt": "Relâmpago",
  "locate-animals-or-plants": "Localizar Animais ou Plantas",
  "locate-creature": "Localizar Criatura",
  "locate-object": "Localizar Objeto",
  "longstrider": "Passos Longos",
  "mage-armor": "Armadura Arcana",
  "mage-hand": "Mão Arcana",
  "magic-circle": "Círculo Mágico",
  "magic-jar": "Jarra Mágica",
  "magic-missile": "Mísseis Mágicos",
  "magic-mouth": "Boca Mágica",
  "magic-weapon": "Arma Mágica",
  "magnificent-mansion": "Mansão Magnífica",
  "major-image": "Imagem Maior",
  "mass-cure-wounds": "Curar Ferimentos em Massa",
  "mass-heal": "Cura em Massa",
  "mass-healing-word": "Palavra Curativa em Massa",
  "mass-suggestion": "Sugestão em Massa",
  "maze": "Labirinto",
  "meld-into-stone": "Fundir-se na Pedra",
  "mending": "Conserto",
  "message": "Mensagem",
  "meteor-swarm": "Enxame de Meteoros",
  "mind-blank": "Limpar a Mente",
  "minor-illusion": "Ilusão Menor",
  "mirage-arcane": "Miragem Arcana",
  "mirror-image": "Imagem Espelhada",
  "mislead": "Engano",
  "misty-step": "Passo Nebuloso",
  "modify-memory": "Modificar Memória",
  "moonbeam": "Raio Lunar",
  "move-earth": "Mover Terra",
  "nondetection": "Indetectável",
  "pass-without-trace": "Passos sem Pegadas",
  "passwall": "Passagem",
  "phantasmal-killer": "Assassino Fantasmagórico",
  "phantom-steed": "Corcel Fantasma",
  "planar-ally": "Aliado Planar",
  "planar-binding": "Vínculo Planar",
  "plane-shift": "Viagem Planar",
  "plant-growth": "Crescer Plantas",
  "poison-spray": "Borrifo de Veneno",
  "polymorph": "Polimorfar",
  "power-word-kill": "Palavra de Poder: Matar",
  "power-word-stun": "Palavra de Poder: Atordoar",
  "prayer-of-healing": "Prece de Cura",
  "prestidigitation": "Prestidigitação",
  "prismatic-spray": "Borrifo Prismático",
  "prismatic-wall": "Parede Prismática",
  "private-sanctum": "Santuário Privado",
  "produce-flame": "Produzir Chamas",
  "programmed-illusion": "Ilusão Programada",
  "project-image": "Projetar Imagem",
  "protection-from-energy": "Proteção contra Energia",
  "protection-from-evil-and-good": "Proteção contra o Bem e o Mal",
  "protection-from-poison": "Proteção contra Veneno",
  "purify-food-and-drink": "Purificar Comida e Bebida",
  "raise-dead": "Reviver Mortos",
  "ray-of-enfeeblement": "Raio de Enfraquecimento",
  "ray-of-frost": "Raio de Gelo",
  "regenerate": "Regeneração",
  "reincarnate": "Reencarnar",
  "remove-curse": "Remover Maldição",
  "resilient-sphere": "Esfera Resiliente",
  "resistance": "Resistência",
  "resurrection": "Ressurreição",
  "reverse-gravity": "Inverter Gravidade",
  "revivify": "Revivificar",
  "rope-trick": "Truque da Corda",
  "sacred-flame": "Chama Sagrada",
  "sanctuary": "Santuário",
  "scorching-ray": "Raio Ardente",
  "scrying": "Vidência",
  "secret-chest": "Baú Secreto",
  "see-invisibility": "Ver o Invisível",
  "seeming": "Aparência",
  "sending": "Enviando",
  "sequester": "Sequestro",
  "shapechange": "Mudar Forma",
  "shatter": "Despedaçar",
  "shield": "Escudo",
  "shield-of-faith": "Escudo da Fé",
  "shillelagh": "Bordão Místico",
  "shocking-grasp": "Aperto Chocante",
  "silence": "Silêncio",
  "silent-image": "Imagem Silenciosa",
  "simulacrum": "Simulacro",
  "sleep": "Sono",
  "sleet-storm": "Tempestade de Granizo",
  "slow": "Lentidão",
  "spare-the-dying": "Poupar os Moribundos",
  "speak-with-animals": "Falar com Animais",
  "speak-with-dead": "Falar com os Mortos",
  "speak-with-plants": "Falar com Plantas",
  "spider-climb": "Escalar como Aranha",
  "spike-growth": "Crescer Espinhos",
  "spirit-guardians": "Guardiões Espirituais",
  "spiritual-weapon": "Arma Espiritual",
  "stinking-cloud": "Nuvem Fétida",
  "stone-shape": "Moldar Rocha",
  "stoneskin": "Pele de Pedra",
  "storm-of-vengeance": "Tempestade Vingativa",
  "suggestion": "Sugestão",
  "sunbeam": "Raio Solar",
  "sunburst": "Explosão Solar",
  "symbol": "Símbolo",
  "telekinesis": "Telecinese",
  "telepathic-bond": "Vínculo Telepático",
  "teleport": "Teletransporte",
  "teleportation-circle": "Círculo de Teletransporte",
  "thaumaturgy": "Taumaturgia",
  "thunderwave": "Onda Trovejante",
  "time-stop": "Parar o Tempo",
  "tiny-hut": "Cabana Diminuta",
  "tongues": "Idiomas",
  "transport-via-plants": "Transporte via Plantas",
  "tree-stride": "Caminhar nas Árvores",
  "true-polymorph": "Polimorfar Verdadeiro",
  "true-resurrection": "Ressurreição Verdadeira",
  "true-seeing": "Visão Verdadeira",
  "true-strike": "Golpe Certeiro",
  "unseen-servant": "Servo Invisível",
  "vampiric-touch": "Toque Vampírico",
  "vicious-mockery": "Zombaria Cruel",
  "wall-of-fire": "Parede de Fogo",
  "wall-of-force": "Parede de Força",
  "wall-of-ice": "Parede de Gelo",
  "wall-of-stone": "Parede de Pedra",
  "wall-of-thorns": "Parede de Espinhos",
  "warding-bond": "Vínculo Protetor",
  "water-breathing": "Respirar na Água",
  "water-walk": "Caminhar na Água",
  "web": "Teia",
  "weird": "Pesadelo",
  "wind-walk": "Caminhar no Vento",
  "wind-wall": "Parede de Vento",
  "wish": "Desejo",
  "word-of-recall": "Palavra de Recordação",
  "zone-of-truth": "Zona da Verdade",
};
