// ══════════════════════════════════════════════════════
// Magias exclusivas do D&D 3.5 — Traduções hardcoded PT-BR
// Magias que NÃO têm equivalente no dicionário 5e
// ══════════════════════════════════════════════════════

export const spellNames35: Record<string, string> = {
  // A
  "acid-fog-35": "Névoa Ácida",
  "air-walk-35": "Caminhar no Ar",
  "align-weapon-35": "Alinhar Arma",
  "analyze-dweomer-35": "Analisar Encantamento",
  "animal-growth-35": "Crescimento Animal",
  "animal-trance-35": "Transe Animal",
  "animate-plants-35": "Animar Plantas",
  "animate-rope-35": "Animar Corda",
  "animus-blast-35": "Explosão de Ânimo",
  "animus-blizzard-35": "Nevasca de Ânimo",
  "antiplant-shell-35": "Escudo Antiplanta",
  "antipathy-35": "Antipatia",
  "arcane-mark-35": "Marca Arcana",
  "arcane-sight-35": "Visão Arcana",
  "arcane-sight-greater-35": "Visão Arcana Superior",
  "armor-of-darkness-35": "Armadura das Trevas",
  "atonement-35": "Penitência",

  // B
  "baleful-transportation-35": "Transporte Funesto",
  "bear-s-endurance-35": "Resistência do Urso",
  "bear-s-endurance-mass-35": "Resistência do Urso em Massa",
  "binding-35": "Confinamento",
  "blasphemy-35": "Blasfêmia",
  "bless-water-35": "Abençoar Água",
  "bless-weapon-35": "Abençoar Arma",
  "bolt-of-glory-35": "Raio de Glória",
  "bolts-of-bedevilment-35": "Raios de Tormento",
  "brain-spider-35": "Aranha Cerebral",
  "bull-s-strength-35": "Força do Touro",
  "bull-s-strength-mass-35": "Força do Touro em Massa",

  // C
  "call-lightning-storm-35": "Invocar Tempestade de Relâmpagos",
  "calm-animals-35": "Acalmar Animais",
  "cat-s-grace-35": "Graça Felina",
  "cat-s-grace-mass-35": "Graça Felina em Massa",
  "cause-fear-35": "Causar Medo",
  "changestaff-35": "Transformar Cajado",
  "chaos-hammer-35": "Martelo do Caos",
  "charm-animal-35": "Enfeitiçar Animal",
  "charm-monster-35": "Enfeitiçar Monstro",
  "charm-monster-mass-35": "Enfeitiçar Monstro em Massa",
  "chill-metal-35": "Gelar Metal",
  "clairaudience-clairvoyance-35": "Clariaudiência/Clarividência",
  "clenched-fist-35": "Punho Cerrado",
  "cloak-of-chaos-35": "Manto do Caos",
  "command-plants-35": "Comandar Plantas",
  "command-undead-35": "Comandar Mortos-Vivos",
  "command-greater-35": "Comando Superior",
  "confusion-lesser-35": "Confusão Menor",
  "consecrate-35": "Consagrar",
  "contingent-resurrection-35": "Ressurreição Contingente",
  "control-plants-35": "Controlar Plantas",
  "control-undead-35": "Controlar Mortos-Vivos",
  "control-winds-35": "Controlar Ventos",
  "corrupt-weapon-35": "Corromper Arma",
  "create-greater-undead-35": "Criar Morto-Vivo Superior",
  "create-living-vault-ritual-35": "Criar Cofre Vivo (Ritual)",
  "create-water-35": "Criar Água",
  "creeping-doom-35": "Perdição Rastejante",
  "crown-of-glory-35": "Coroa de Glória",
  "crown-of-vermin-35": "Coroa de Vermes",
  "crushing-despair-35": "Desespero Esmagador",
  "crushing-hand-35": "Mão Esmagadora",
  "cure-critical-wounds-mass-35": "Curar Ferimentos Críticos em Massa",
  "cure-light-wounds-mass-35": "Curar Ferimentos Leves em Massa",
  "cure-minor-wounds-35": "Curar Ferimentos Mínimos",
  "cure-moderate-wounds-mass-35": "Curar Ferimentos Moderados em Massa",
  "cure-serious-wounds-mass-35": "Curar Ferimentos Graves em Massa",
  "curse-water-35": "Amaldiçoar Água",

  // D
  "damnation-35": "Danação",
  "daze-monster-35": "Aturdir Monstro",
  "death-knell-35": "Dobre de Finados",
  "deathwatch-35": "Sentinela da Morte",
  "deep-slumber-35": "Sono Profundo",
  "deeper-darkness-35": "Escuridão Profunda",
  "delay-poison-35": "Retardar Veneno",
  "demand-35": "Exigência",
  "demise-unseen-35": "Morte Invisível",
  "desecrate-35": "Profanar",
  "destruction-35": "Destruição",
  "detect-animals-or-plants-35": "Detectar Animais ou Plantas",
  "detect-chaos-35": "Detectar Caos",
  "detect-good-35": "Detectar o Bem",
  "detect-law-35": "Detectar Lei",
  "detect-scrying-35": "Detectar Vidência",
  "detect-secret-doors-35": "Detectar Portas Secretas",
  "detect-snares-and-pits-35": "Detectar Armadilhas e Fossos",
  "detect-undead-35": "Detectar Mortos-Vivos",
  "dictum-35": "Decreto",
  "dimensional-anchor-35": "Âncora Dimensional",
  "dimensional-lock-35": "Bloqueio Dimensional",
  "diminish-plants-35": "Diminuir Plantas",
  "dire-winter-35": "Inverno Terrível",
  "discern-lies-35": "Discernir Mentiras",
  "discern-location-35": "Discernir Localização",
  "dismissal-35": "Banir",
  "dispel-chaos-35": "Dissipar Caos",
  "dispel-evil-35": "Dissipar o Mal",
  "dispel-good-35": "Dissipar o Bem",
  "dispel-law-35": "Dissipar Lei",
  "dispel-magic-greater-35": "Dissipar Magia Superior",
  "displacement-35": "Deslocamento",
  "disrupting-weapon-35": "Arma Disruptiva",
  "dominate-animal-35": "Dominar Animal",
  "doom-35": "Perdição",
  "dragon-knight-ritual-35": "Cavaleiro Dragão (Ritual)",
  "dragon-strike-ritual-35": "Golpe do Dragão (Ritual)",
  "dreamscape-35": "Paisagem Onírica",
  "dweomer-of-transference-35": "Encantamento de Transferência",

  // E
  "eagle-s-splendor-35": "Esplendor da Águia",
  "eagle-s-splendor-mass-35": "Esplendor da Águia em Massa",
  "eclipse-35": "Eclipse",
  "eidolon-35": "Eidolon",
  "elemental-swarm-35": "Enxame Elemental",
  "endure-elements-35": "Suportar Elementos",
  "energy-drain-35": "Drenar Energia",
  "enervation-35": "Enervação",
  "enlarge-person-mass-35": "Aumentar Pessoa em Massa",
  "enslave-ritual-35": "Escravizar (Ritual)",
  "entropic-shield-35": "Escudo Entrópico",
  "epic-counterspell-35": "Contramágica Épica",
  "epic-mage-armor-35": "Armadura Arcana Épica",
  "epic-repulsion-35": "Repulsão Épica",
  "epic-spell-reflection-35": "Reflexão de Magia Épica",
  "erase-35": "Apagar",
  "eternal-freedom-35": "Liberdade Eterna",
  "ethereal-jaunt-35": "Excursão Etérea",
  "explosive-runes-35": "Runas Explosivas",

  // F
  "false-vision-35": "Visão Falsa",
  "fire-seeds-35": "Sementes de Fogo",
  "fire-trap-35": "Armadilha de Fogo",
  "flame-arrow-35": "Flecha Flamejante",
  "forceful-hand-35": "Mão Vigorosa",
  "fox-s-cunning-35": "Astúcia da Raposa",
  "fox-s-cunning-mass-35": "Astúcia da Raposa em Massa",
  "freedom-35": "Liberdade",

  // G
  "gathering-of-maggots-35": "Congregação de Larvas",
  "geas-lesser-35": "Missão Menor",
  "geas-quest-35": "Missão/Busca",
  "genesis-35": "Gênese",
  "ghoul-touch-35": "Toque de Carniçal",
  "giant-vermin-35": "Verme Gigante",
  "glitterdust-35": "Pó Brilhante",
  "globe-of-invulnerability-lesser-35": "Globo de Invulnerabilidade Menor",
  "glossolalia-35": "Glossolalia",
  "glyph-of-warding-greater-35": "Glifo de Proteção Superior",
  "good-hope-35": "Boa Esperança",
  "grasping-hand-35": "Mão Agarradora",
  "greater-ruin-35": "Ruína Superior",
  "greater-spell-resistance-35": "Resistência a Magia Superior",

  // H
  "halt-undead-35": "Deter Mortos-Vivos",
  "hardening-35": "Endurecimento",
  "heal-mount-35": "Curar Montaria",
  "heal-mass-35": "Cura em Massa",
  "hellball-35": "Esfera Infernal",
  "helping-hand-35": "Mão Amiga",
  "heroism-greater-35": "Heroísmo Superior",
  "hide-from-animals-35": "Esconder-se de Animais",
  "hide-from-undead-35": "Esconder-se de Mortos-Vivos",
  "hold-animal-35": "Imobilizar Animal",
  "hold-monster-mass-35": "Imobilizar Monstro em Massa",
  "hold-person-mass-35": "Imobilizar Pessoa em Massa",
  "hold-portal-35": "Trancar Portal",
  "holy-smite-35": "Golpe Sagrado",
  "holy-sword-35": "Espada Sagrada",
  "holy-word-35": "Palavra Sagrada",
  "hypnotism-35": "Hipnotismo",

  // I
  "illusory-wall-35": "Parede Ilusória",
  "imbue-with-spell-ability-35": "Imbuir com Habilidade Mágica",
  "implosion-35": "Implosão",
  "inflict-critical-wounds-35": "Infligir Ferimentos Críticos",
  "inflict-critical-wounds-mass-35": "Infligir Ferimentos Críticos em Massa",
  "inflict-light-wounds-35": "Infligir Ferimentos Leves",
  "inflict-light-wounds-mass-35": "Infligir Ferimentos Leves em Massa",
  "inflict-minor-wounds-35": "Infligir Ferimentos Mínimos",
  "inflict-moderate-wounds-35": "Infligir Ferimentos Moderados",
  "inflict-moderate-wounds-mass-35": "Infligir Ferimentos Moderados em Massa",
  "inflict-serious-wounds-35": "Infligir Ferimentos Graves",
  "inflict-serious-wounds-mass-35": "Infligir Ferimentos Graves em Massa",
  "insanity-35": "Insanidade",
  "interposing-hand-35": "Mão Interposta",
  "invisibility-purge-35": "Purgar Invisibilidade",
  "invisibility-sphere-35": "Esfera de Invisibilidade",
  "invisibility-greater-35": "Invisibilidade Superior",
  "invisibility-mass-35": "Invisibilidade em Massa",
  "iron-body-35": "Corpo de Ferro",
  "ironwood-35": "Madeira de Ferro",

  // K
  "keen-edge-35": "Afiação",
  "kinetic-control-35": "Controle Cinético",
  "know-direction-35": "Saber a Direção",

  // L
  "let-go-of-me-35": "Solte-me",
  "limited-wish-35": "Desejo Limitado",
  "liveoak-35": "Carvalho Vivo",
  "living-lightning-35": "Relâmpago Vivo",
  "lord-of-nightmares-35": "Senhor dos Pesadelos",
  "lullaby-35": "Canção de Ninar",

  // M
  "maddening-scream-35": "Grito Enlouquecedor",
  "mage-s-disjunction-35": "Disjunção do Mago",
  "mage-s-faithful-hound-35": "Cão Fiel do Mago",
  "mage-s-lucubration-35": "Elucubração do Mago",
  "mage-s-magnificent-mansion-35": "Mansão Magnífica do Mago",
  "mage-s-private-sanctum-35": "Santuário Privado do Mago",
  "mage-s-sword-35": "Espada do Mago",
  "magic-aura-35": "Aura Mágica",
  "magic-circle-against-chaos-35": "Círculo Mágico contra o Caos",
  "magic-circle-against-good-35": "Círculo Mágico contra o Bem",
  "magic-circle-against-law-35": "Círculo Mágico contra a Lei",
  "magic-fang-35": "Presa Mágica",
  "magic-fang-greater-35": "Presa Mágica Superior",
  "magic-stone-35": "Pedra Mágica",
  "magic-vestment-35": "Vestimenta Mágica",
  "magic-weapon-greater-35": "Arma Mágica Superior",
  "major-creation-35": "Criação Maior",
  "make-whole-35": "Restaurar Inteiro",
  "mark-of-justice-35": "Marca da Justiça",
  "mass-frog-35": "Sapo em Massa",
  "mental-pinnacle-35": "Pináculo Mental",
  "mind-fog-35": "Névoa Mental",
  "minor-creation-35": "Criação Menor",
  "minor-image-35": "Ilusão Menor",
  "miracle-35": "Milagre",
  "misdirection-35": "Desorientação",
  "mnemonic-enhancer-35": "Intensificador Mnemônico",
  "moment-of-prescience-35": "Momento de Presciência",
  "momento-mori-35": "Memento Mori",
  "mount-35": "Montaria",
  "mummy-dust-35": "Pó de Múmia",

  // N
  "nailed-to-the-sky-35": "Pregado no Céu",
  "neutralize-poison-35": "Neutralizar Veneno",
  "nightmare-35": "Pesadelo",

  // O
  "obscure-object-35": "Obscurecer Objeto",
  "obscuring-mist-35": "Névoa Obscurecedora",
  "open-close-35": "Abrir/Fechar",
  "order-s-wrath-35": "Ira da Ordem",
  "origin-of-species-achaierai-35": "Origem das Espécies: Achaierai",
  "overland-flight-35": "Voo Terrestre",
  "owl-s-wisdom-35": "Sabedoria da Coruja",
  "owl-s-wisdom-mass-35": "Sabedoria da Coruja em Massa",

  // P
  "permanency-35": "Permanência",
  "permanent-image-35": "Imagem Permanente",
  "persistent-image-35": "Imagem Persistente",
  "pestilence-35": "Pestilência",
  "peripety-35": "Peripécia",
  "phantom-trap-35": "Armadilha Fantasma",
  "phase-door-35": "Porta de Fase",
  "planar-ally-greater-35": "Aliado Planar Superior",
  "planar-ally-lesser-35": "Aliado Planar Menor",
  "planar-binding-greater-35": "Vínculo Planar Superior",
  "planar-binding-lesser-35": "Vínculo Planar Menor",
  "poison-35": "Veneno",
  "polar-ray-35": "Raio Polar",
  "polymorph-any-object-35": "Polimorfar Qualquer Objeto",
  "power-word-blind-35": "Palavra de Poder: Cegar",
  "prismatic-sphere-35": "Esfera Prismática",
  "probe-thoughts-35": "Sondar Pensamentos",
  "programmed-image-35": "Imagem Programada",
  "protection-from-arrows-35": "Proteção contra Flechas",
  "protection-from-chaos-35": "Proteção contra o Caos",
  "protection-from-good-35": "Proteção contra o Bem",
  "protection-from-law-35": "Proteção contra a Lei",
  "protection-from-spells-35": "Proteção contra Magias",
  "prying-eyes-35": "Olhos Bisbilhoteiros",
  "prying-eyes-greater-35": "Olhos Bisbilhoteiros Superiores",
  "psychic-turmoil-35": "Tumulto Psíquico",
  "psychic-turmoil-greater-35": "Tumulto Psíquico Superior",
  "pyrotechnics-35": "Pirotecnia",

  // Q
  "quench-35": "Extinguir",

  // R
  "rage-35": "Fúria",
  "rain-of-fire-35": "Chuva de Fogo",
  "rainbow-pattern-35": "Padrão Arco-Íris",
  "raise-island-35": "Erguer Ilha",
  "ray-of-exhaustion-35": "Raio de Exaustão",
  "reduce-animal-35": "Reduzir Animal",
  "reduce-person-35": "Reduzir Pessoa",
  "reduce-person-mass-35": "Reduzir Pessoa em Massa",
  "refuge-35": "Refúgio",
  "remove-blindness-deafness-35": "Remover Cegueira/Surdez",
  "remove-disease-35": "Remover Doença",
  "remove-fear-35": "Remover Medo",
  "remove-paralysis-35": "Remover Paralisia",
  "repel-metal-or-stone-35": "Repelir Metal ou Pedra",
  "repel-vermin-35": "Repelir Vermes",
  "repel-wood-35": "Repelir Madeira",
  "repulsion-35": "Repulsão",
  "restoration-35": "Restauração",
  "restoration-greater-35": "Restauração Superior",
  "restoration-lesser-35": "Restauração Menor",
  "righteous-might-35": "Poder Virtuoso",
  "ruin-35": "Ruína",
  "rusting-grasp-35": "Aperto Oxidante",

  // S
  "safe-time-35": "Tempo Seguro",
  "scare-35": "Assustar",
  "scintillating-pattern-35": "Padrão Cintilante",
  "screen-35": "Biombo",
  "scrying-greater-35": "Vidência Superior",
  "sculpt-sound-35": "Esculpir Som",
  "searing-light-35": "Luz Abrasadora",
  "secret-page-35": "Página Secreta",
  "secure-shelter-35": "Abrigo Seguro",
  "sepia-snake-sigil-35": "Sigilo de Serpente Sépia",
  "shades-35": "Sombras",
  "shadow-conjuration-35": "Conjuração das Sombras",
  "shadow-conjuration-greater-35": "Conjuração das Sombras Superior",
  "shadow-evocation-35": "Evocação das Sombras",
  "shadow-evocation-greater-35": "Evocação das Sombras Superior",
  "shadow-walk-35": "Caminhar nas Sombras",
  "shambler-35": "Rastejante",
  "shield-other-35": "Proteger Outro",
  "shield-of-law-35": "Escudo da Lei",
  "shout-35": "Grito",
  "shout-greater-35": "Grito Superior",
  "shrink-item-35": "Encolher Item",
  "slay-living-35": "Matar Vivente",
  "snare-35": "Laço",
  "soften-earth-and-stone-35": "Amolecer Terra e Pedra",
  "solid-fog-35": "Névoa Sólida",
  "song-of-discord-35": "Canção de Discórdia",
  "soul-bind-35": "Aprisionar Alma",
  "soul-dominion-35": "Domínio da Alma",
  "soul-scry-35": "Vidência da Alma",
  "sound-burst-35": "Explosão Sonora",
  "spectral-hand-35": "Mão Espectral",
  "spell-immunity-35": "Imunidade a Magia",
  "spell-immunity-greater-35": "Imunidade a Magia Superior",
  "spell-resistance-35": "Resistência a Magia",
  "spell-worm-35": "Verme Mágico",
  "spellstaff-35": "Cajado Mágico",
  "spike-stones-35": "Pedras Pontiagudas",
  "statue-35": "Estátua",
  "status-35": "Estado",
  "status-greater-35": "Estado Superior",
  "stone-tell-35": "Falar com Pedras",
  "stone-to-flesh-35": "Pedra para Carne",
  "suggestion-mass-35": "Sugestão em Massa",
  "summon-behemoth-35": "Conjurar Behemoth",
  "summon-instrument-35": "Conjurar Instrumento",
  "summon-monster-i-35": "Conjurar Monstro I",
  "summon-monster-ii-35": "Conjurar Monstro II",
  "summon-monster-iii-35": "Conjurar Monstro III",
  "summon-monster-iv-35": "Conjurar Monstro IV",
  "summon-monster-v-35": "Conjurar Monstro V",
  "summon-monster-vi-35": "Conjurar Monstro VI",
  "summon-monster-vii-35": "Conjurar Monstro VII",
  "summon-monster-viii-35": "Conjurar Monstro VIII",
  "summon-monster-ix-35": "Conjurar Monstro IX",
  "summon-nature-s-ally-i-35": "Conjurar Aliado da Natureza I",
  "summon-nature-s-ally-ii-35": "Conjurar Aliado da Natureza II",
  "summon-nature-s-ally-iii-35": "Conjurar Aliado da Natureza III",
  "summon-nature-s-ally-iv-35": "Conjurar Aliado da Natureza IV",
  "summon-nature-s-ally-v-35": "Conjurar Aliado da Natureza V",
  "summon-nature-s-ally-vi-35": "Conjurar Aliado da Natureza VI",
  "summon-nature-s-ally-vii-35": "Conjurar Aliado da Natureza VII",
  "summon-nature-s-ally-viii-35": "Conjurar Aliado da Natureza VIII",
  "summon-nature-s-ally-ix-35": "Conjurar Aliado da Natureza IX",
  "summon-swarm-35": "Conjurar Enxame",
  "superb-dispelling-35": "Dissipação Soberba",
  "surelife-35": "Vida Segura",
  "symbol-of-death-35": "Símbolo de Morte",
  "symbol-of-fear-35": "Símbolo de Medo",
  "symbol-of-insanity-35": "Símbolo de Insanidade",
  "symbol-of-pain-35": "Símbolo de Dor",
  "symbol-of-persuasion-35": "Símbolo de Persuasão",
  "symbol-of-sleep-35": "Símbolo de Sono",
  "symbol-of-stunning-35": "Símbolo de Atordoamento",
  "symbol-of-weakness-35": "Símbolo de Fraqueza",
  "sympathetic-vibration-35": "Vibração Simpática",
  "sympathy-35": "Simpatia",

  // T
  "telekinetic-sphere-35": "Esfera Telecinética",
  "telepathic-bond-lesser-35": "Vínculo Telepático Menor",
  "teleport-object-35": "Teletransportar Objeto",
  "teleport-greater-35": "Teletransporte Superior",
  "temporal-stasis-35": "Estase Temporal",
  "time-duplicate-35": "Duplicata Temporal",
  "touch-of-madness-35": "Toque da Loucura",
  "touch-of-fatigue-35": "Toque de Fadiga",
  "touch-of-idiocy-35": "Toque de Idiotice",
  "transformation-35": "Transformação",
  "transmute-metal-to-wood-35": "Transmutar Metal em Madeira",
  "transmute-mud-to-rock-35": "Transmutar Lama em Rocha",
  "transmute-rock-to-mud-35": "Transmutar Rocha em Lama",
  "trap-the-soul-35": "Aprisionar a Alma",
  "tree-shape-35": "Forma de Árvore",
  "true-creation-35": "Criação Verdadeira",

  // U
  "undeath-to-death-35": "Vida dos Mortos-Vivos",
  "undetectable-alignment-35": "Alinhamento Indetectável",
  "unhallow-35": "Dessagrar",
  "unholy-aura-35": "Aura Profana",
  "unholy-blight-35": "Praga Profana",

  // V
  "veil-35": "Véu",
  "vengeful-gaze-of-god-35": "Olhar Vingativo de Deus",
  "ventriloquism-35": "Ventriloquismo",
  "verdigris-35": "Verdete",
  "verdigris-tsunami-35": "Tsunami de Verdete",
  "vision-35": "Visão",

  // W
  "wail-of-the-banshee-35": "Lamento da Banshee",
  "wall-of-iron-35": "Parede de Ferro",
  "warp-wood-35": "Deformar Madeira",
  "waves-of-exhaustion-35": "Ondas de Exaustão",
  "waves-of-fatigue-35": "Ondas de Fadiga",
  "whirlwind-35": "Redemoinho",
  "whispering-wind-35": "Vento Sussurrante",
  "wood-shape-35": "Moldar Madeira",
  "word-of-chaos-35": "Palavra do Caos",
  "zone-of-silence-35": "Zona de Silêncio",
};
