// Nomes PT-BR de Classes
export const classNames: Record<string, string> = {
  // 5e core
  "barbarian": "Bárbaro",
  "bard": "Bardo",
  "cleric": "Clérigo",
  "druid": "Druida",
  "fighter": "Guerreiro",
  "monk": "Monge",
  "paladin": "Paladino",
  "ranger": "Patrulheiro",
  "rogue": "Ladino",
  "sorcerer": "Feiticeiro",
  "warlock": "Bruxo",
  "wizard": "Mago",
  // 3.5 core
  "barbarian-35": "Bárbaro",
  "bard-35": "Bardo",
  "cleric-35": "Clérigo",
  "druid-35": "Druida",
  "fighter-35": "Guerreiro",
  "monk-35": "Monge",
  "paladin-35": "Paladino",
  "ranger-35": "Patrulheiro",
  "rogue-35": "Ladino",
  "sorcerer-35": "Feiticeiro",
  "wizard-35": "Mago",
  // 3.5 prestige / NPC
  "arcane-archer-35": "Arqueiro Arcano",
  "arcane-trickster-35": "Trapaceiro Arcano",
  "archmage-35": "Arquimago",
  "assassin-35": "Assassino",
  "blackguard-35": "Cavaleiro Negro",
  "dwarven-defender-35": "Defensor Anão",
  "eldritch-knight-35": "Cavaleiro Arcano",
  "mystic-theurge-35": "Teurgo Místico",
  // 3.5 NPC
  "adept-npc-35": "Adepto (NPC)",
  "aristocrat-npc-35": "Aristocrata (NPC)",
  "commoner-npc-35": "Plebeu (NPC)",
  "expert-npc-35": "Especialista (NPC)",
  "warrior-npc-35": "Guerreiro (NPC)",
  // 3.5 Psionic
  "psion-egoist-35": "Psion (Egoísta)",
  "psion-kineticist-35": "Psion (Cinecista)",
  "psion-nomad-35": "Psion (Nômade)",
  "psion-seer-35": "Psion (Vidente)",
  "psion-shaper-35": "Psion (Modelador)",
  "psion-telepath-35": "Psion (Telepata)",
  "psychic-warrior-35": "Guerreiro Psíquico",
  "soulknife-35": "Soulknife",
  "wilder-35": "Wilder",
};

// Nomes PT-BR de Condições
export const conditionNames: Record<string, string> = {
  // 5e
  "blinded": "Cego",
  "charmed": "Enfeitiçado",
  "deafened": "Surdo",
  "exhaustion": "Exausto",
  "frightened": "Amedrontado",
  "grappled": "Agarrado",
  "incapacitated": "Incapacitado",
  "invisible": "Invisível",
  "paralyzed": "Paralisado",
  "petrified": "Petrificado",
  "poisoned": "Envenenado",
  "prone": "Caído",
  "restrained": "Contido",
  "stunned": "Atordoado",
  "unconscious": "Inconsciente",
  // 3.5
  "ability-damaged-35": "Habilidade Danificada",
  "ability-drained-35": "Habilidade Drenada",
  "blinded-35": "Cego",
  "blown-away-35": "Arremessado",
  "checked-35": "Barrado",
  "confused-35": "Confuso",
  "cowering-35": "Acovardado",
  "dazed-35": "Aturdido",
  "dazzled-35": "Ofuscado",
  "dead-35": "Morto",
  "deafened-35": "Surdo",
  "disabled-35": "Debilitado",
  "dying-35": "Morrendo",
  "energy-drained-35": "Energia Drenada",
  "entangled-35": "Enredado",
  "exhausted-35": "Exausto",
  "fascinated-35": "Fascinado",
  "fatigued-35": "Fatigado",
  "flat-footed-35": "Surpreendido",
  "frightened-35": "Amedrontado",
  "grappling-35": "Agarrando",
  "helpless-35": "Indefeso",
  "incorporeal-35": "Incorpóreo",
  "invisible-35": "Invisível",
  "knocked-down-35": "Derrubado",
  "nauseated-35": "Nauseado",
  "panicked-35": "Em Pânico",
  "paralyzed-35": "Paralisado",
  "petrified-35": "Petrificado",
  "pinned-35": "Imobilizado",
  "prone-35": "Caído",
  "shaken-35": "Abalado",
  "sickened-35": "Enojado",
  "stable-35": "Estável",
  "staggered-35": "Cambaleante",
  "stunned-35": "Atordoado",
  "turned-35": "Expulso",
  "unconscious-35": "Inconsciente",
};

// Nomes PT-BR de Skills (5e)
export const skillNames: Record<string, string> = {
  "acrobatics": "Acrobacia",
  "animal-handling": "Trato com Animais",
  "arcana": "Arcanismo",
  "athletics": "Atletismo",
  "deception": "Enganação",
  "history": "História",
  "insight": "Intuição",
  "intimidation": "Intimidação",
  "investigation": "Investigação",
  "medicine": "Medicina",
  "nature": "Natureza",
  "perception": "Percepção",
  "performance": "Atuação",
  "persuasion": "Persuasão",
  "religion": "Religião",
  "sleight-of-hand": "Prestidigitação",
  "stealth": "Furtividade",
  "survival": "Sobrevivência",
};

// Nomes PT-BR de Idiomas
export const languageNames: Record<string, string> = {
  "abyssal": "Abissal",
  "celestial": "Celestial",
  "common": "Comum",
  "deep-speech": "Fala Profunda",
  "draconic": "Dracônico",
  "dwarvish": "Anão",
  "elvish": "Élfico",
  "giant": "Gigante",
  "gnomish": "Gnômico",
  "goblin": "Goblin",
  "halfling": "Halfling",
  "infernal": "Infernal",
  "orc": "Orc",
  "primordial": "Primordial",
  "sylvan": "Silvano",
  "undercommon": "Subcomum",
};

// Nomes PT-BR de Traits Raciais
export const traitNames: Record<string, string> = {
  "artificers-lore": "Tradição do Artífice",
  "brave": "Bravura",
  "breath-weapon": "Arma de Sopro",
  "damage-resistance": "Resistência a Dano",
  "darkvision": "Visão no Escuro",
  "draconic-ancestry": "Ancestralidade Dracônica",
  "draconic-ancestry-black": "Ancestralidade Dracônica (Negro)",
  "draconic-ancestry-blue": "Ancestralidade Dracônica (Azul)",
  "draconic-ancestry-brass": "Ancestralidade Dracônica (Latão)",
  "draconic-ancestry-bronze": "Ancestralidade Dracônica (Bronze)",
  "draconic-ancestry-copper": "Ancestralidade Dracônica (Cobre)",
  "draconic-ancestry-gold": "Ancestralidade Dracônica (Ouro)",
  "draconic-ancestry-green": "Ancestralidade Dracônica (Verde)",
  "draconic-ancestry-red": "Ancestralidade Dracônica (Vermelho)",
  "draconic-ancestry-silver": "Ancestralidade Dracônica (Prata)",
  "draconic-ancestry-white": "Ancestralidade Dracônica (Branco)",
  "dwarven-combat-training": "Treinamento de Combate Anão",
  "dwarven-resilience": "Resiliência Anã",
  "dwarven-toughness": "Tenacidade Anã",
  "elf-weapon-training": "Treinamento com Armas Élficas",
  "extra-language": "Idioma Adicional",
  "fey-ancestry": "Ancestralidade Feérica",
  "gnome-cunning": "Astúcia Gnômica",
  "halfling-nimbleness": "Agilidade Halfling",
  "hellish-resistance": "Resistência Infernal",
  "high-elf-cantrip": "Truque de Alto Elfo",
  "infernal-legacy": "Legado Infernal",
  "keen-senses": "Sentidos Aguçados",
  "lucky": "Sortudo",
  "menacing": "Ameaçador",
  "naturally-stealthy": "Naturalmente Furtivo",
  "relentless-endurance": "Resistência Implacável",
  "savage-attacks": "Ataques Selvagens",
  "skill-versatility": "Versatilidade em Perícias",
  "stonecunning": "Especialização em Pedra",
  "tinker": "Engenhoqueiro",
  "tool-proficiency": "Proficiência com Ferramentas",
  "trance": "Transe",
};

// Nomes PT-BR de Subclasses
export const subclassNames: Record<string, string> = {
  "berserker": "Berserker",
  "champion": "Campeão",
  "devotion": "Devoção",
  "draconic": "Dracônico",
  "evocation": "Evocação",
  "fiend": "Corruptor",
  "hunter": "Caçador",
  "land": "Terra",
  "life": "Vida",
  "lore": "Conhecimento",
  "open-hand": "Mão Aberta",
  "thief": "Ladrão",
};

// Nomes PT-BR de Sub-raças
export const subraceNames: Record<string, string> = {
  "high-elf": "Alto Elfo",
  "hill-dwarf": "Anão da Colina",
  "lightfoot-halfling": "Halfling Pés-Leves",
  "rock-gnome": "Gnomo das Rochas",
};

// Nomes PT-BR de Raças
export const raceNames: Record<string, string> = {
  "dragonborn": "Draconato",
  "dwarf": "Anão",
  "elf": "Elfo",
  "gnome": "Gnomo",
  "half-elf": "Meio-Elfo",
  "half-orc": "Meio-Orc",
  "halfling": "Halfling",
  "human": "Humano",
  "tiefling": "Tiefling",
  // 3.5
  "dwarf-35": "Anão",
  "elf-35": "Elfo",
  "gnome-35": "Gnomo",
  "halfling-35": "Halfling",
  "half-elf-35": "Meio-Elfo",
  "half-orc-35": "Meio-Orc",
  "human-35": "Humano",
};
